/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`secret_sessions_service_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SecretSessionsServiceGetError {
    Status403(models::AuthenticationFailedResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalServerErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`secret_sessions_service_get_secret_session_by_secret_session_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SecretSessionsServiceGetSecretSessionBySecretSessionIdError {
    Status403(models::AuthenticationFailedResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalServerErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`secret_sessions_service_get_session_frames`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SecretSessionsServiceGetSessionFramesError {
    Status403(models::AuthenticationFailedResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalServerErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`secret_sessions_service_get_session_image`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SecretSessionsServiceGetSessionImageError {
    Status403(models::AuthenticationFailedResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalServerErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`secret_sessions_service_get_session_image_by_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SecretSessionsServiceGetSessionImageByKeyError {
    Status403(models::AuthenticationFailedResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalServerErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`secret_sessions_service_get_session_image_launcher_guid`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SecretSessionsServiceGetSessionImageLauncherGuidError {
    Status403(models::AuthenticationFailedResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalServerErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`secret_sessions_service_get_session_recording`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SecretSessionsServiceGetSessionRecordingError {
    Status403(models::AuthenticationFailedResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalServerErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`secret_sessions_service_get_session_recording_by_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SecretSessionsServiceGetSessionRecordingByIdError {
    Status403(models::AuthenticationFailedResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalServerErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`secret_sessions_service_get_ssh_proxy_data`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SecretSessionsServiceGetSshProxyDataError {
    Status403(models::AuthenticationFailedResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalServerErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`secret_sessions_service_get_ssh_proxy_data_as_file`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SecretSessionsServiceGetSshProxyDataAsFileError {
    Status403(models::AuthenticationFailedResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalServerErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`secret_sessions_service_get_summary`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SecretSessionsServiceGetSummaryError {
    Status403(models::AuthenticationFailedResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalServerErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`secret_sessions_service_process_session`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SecretSessionsServiceProcessSessionError {
    Status403(models::AuthenticationFailedResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalServerErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`secret_sessions_service_search_points_of_interest`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SecretSessionsServiceSearchPointsOfInterestError {
    Status403(models::AuthenticationFailedResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalServerErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`secret_sessions_service_search_points_of_interest_summary`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SecretSessionsServiceSearchPointsOfInterestSummaryError {
    Status403(models::AuthenticationFailedResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalServerErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`secret_sessions_service_search_sessions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SecretSessionsServiceSearchSessionsError {
    Status403(models::AuthenticationFailedResponse),
    Status400(models::BadRequestResponse),
    Status500(models::InternalServerErrorResponse),
    UnknownValue(serde_json::Value),
}


/// Get a single recorded session by ID
pub async fn secret_sessions_service_get(configuration: &configuration::Configuration, id: &str) -> Result<models::SecretSessionModel, Error<SecretSessionsServiceGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/v1/recorded-sessions/{id}", configuration.base_path, id=crate::apis::urlencode(p_path_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::SecretSessionModel`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::SecretSessionModel`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SecretSessionsServiceGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get a summary of the secret session data
pub async fn secret_sessions_service_get_secret_session_by_secret_session_id(configuration: &configuration::Configuration, id: i32) -> Result<models::SecretSessionSummaryModel, Error<SecretSessionsServiceGetSecretSessionBySecretSessionIdError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/v1/secret-sessions/{id}/summary", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::SecretSessionSummaryModel`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::SecretSessionSummaryModel`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SecretSessionsServiceGetSecretSessionBySecretSessionIdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get Session Frames
pub async fn secret_sessions_service_get_session_frames(configuration: &configuration::Configuration, secret_session_id: i32, top_image_id_recovered: i32) -> Result<Vec<models::SessionFrameModel>, Error<SecretSessionsServiceGetSessionFramesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_secret_session_id = secret_session_id;
    let p_path_top_image_id_recovered = top_image_id_recovered;

    let uri_str = format!("{}/v1/recorded-sessions/session-frames/{secretSessionId}/{topImageIdRecovered}", configuration.base_path, secretSessionId=p_path_secret_session_id, topImageIdRecovered=p_path_top_image_id_recovered);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::SessionFrameModel&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::SessionFrameModel&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SecretSessionsServiceGetSessionFramesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get Session Image
pub async fn secret_sessions_service_get_session_image(configuration: &configuration::Configuration, secret_session_id: i32, image_id: Option<i32>) -> Result<models::FileContentResult, Error<SecretSessionsServiceGetSessionImageError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_secret_session_id = secret_session_id;
    let p_query_image_id = image_id;

    let uri_str = format!("{}/v1/recorded-sessions/session-image/{secretSessionId}", configuration.base_path, secretSessionId=p_path_secret_session_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_image_id {
        req_builder = req_builder.query(&[("imageId", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FileContentResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FileContentResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SecretSessionsServiceGetSessionImageError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get Session Image By the Session Key
pub async fn secret_sessions_service_get_session_image_by_key(configuration: &configuration::Configuration, secret_session_key: &str, image_id: Option<i32>) -> Result<models::FileContentResult, Error<SecretSessionsServiceGetSessionImageByKeyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_secret_session_key = secret_session_key;
    let p_query_image_id = image_id;

    let uri_str = format!("{}/v1/recorded-sessions/session-image-by-key/{secretSessionKey}", configuration.base_path, secretSessionKey=crate::apis::urlencode(p_path_secret_session_key));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_image_id {
        req_builder = req_builder.query(&[("imageId", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FileContentResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FileContentResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SecretSessionsServiceGetSessionImageByKeyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get Session Image By the Launcher Session Guid
pub async fn secret_sessions_service_get_session_image_launcher_guid(configuration: &configuration::Configuration, launcher_guid: &str, image_id: Option<i32>) -> Result<models::FileContentResult, Error<SecretSessionsServiceGetSessionImageLauncherGuidError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_launcher_guid = launcher_guid;
    let p_query_image_id = image_id;

    let uri_str = format!("{}/v1/recorded-sessions/session-image-by-launcher-guid/{launcherGuid}", configuration.base_path, launcherGuid=crate::apis::urlencode(p_path_launcher_guid));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_image_id {
        req_builder = req_builder.query(&[("imageId", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FileContentResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FileContentResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SecretSessionsServiceGetSessionImageLauncherGuidError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get the video stream for a recorded session
pub async fn secret_sessions_service_get_session_recording(configuration: &configuration::Configuration, file_name: &str, id: &str) -> Result<serde_json::Value, Error<SecretSessionsServiceGetSessionRecordingError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_file_name = file_name;
    let p_path_id = id;

    let uri_str = format!("{}/v1/recorded-sessions/{id}/session-recordings/{fileName}", configuration.base_path, fileName=crate::apis::urlencode(p_path_file_name), id=crate::apis::urlencode(p_path_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `serde_json::Value`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `serde_json::Value`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SecretSessionsServiceGetSessionRecordingError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get the video stream for a recorded session by ID
pub async fn secret_sessions_service_get_session_recording_by_id(configuration: &configuration::Configuration, id: &str) -> Result<serde_json::Value, Error<SecretSessionsServiceGetSessionRecordingByIdError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/v1/recorded-sessions/{id}/session-recordings", configuration.base_path, id=crate::apis::urlencode(p_path_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `serde_json::Value`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `serde_json::Value`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SecretSessionsServiceGetSessionRecordingByIdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get the SSH proxy session data
pub async fn secret_sessions_service_get_ssh_proxy_data(configuration: &configuration::Configuration, audit_secret_id: Option<i32>, byte_limit: Option<i64>, filter_type: Option<&str>, search_term: Option<&str>, secret_session_id: Option<i32>, secret_session_key: Option<&str>, session_guid: Option<&str>) -> Result<models::SshProxyDataSearchViewModel, Error<SecretSessionsServiceGetSshProxyDataError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_audit_secret_id = audit_secret_id;
    let p_query_byte_limit = byte_limit;
    let p_query_filter_type = filter_type;
    let p_query_search_term = search_term;
    let p_query_secret_session_id = secret_session_id;
    let p_query_secret_session_key = secret_session_key;
    let p_query_session_guid = session_guid;

    let uri_str = format!("{}/v1/recorded-sessions/ssh-session", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_audit_secret_id {
        req_builder = req_builder.query(&[("auditSecretId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_byte_limit {
        req_builder = req_builder.query(&[("byteLimit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filter_type {
        req_builder = req_builder.query(&[("filterType", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_search_term {
        req_builder = req_builder.query(&[("searchTerm", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_secret_session_id {
        req_builder = req_builder.query(&[("secretSessionId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_secret_session_key {
        req_builder = req_builder.query(&[("secretSessionKey", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_session_guid {
        req_builder = req_builder.query(&[("sessionGuid", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::SshProxyDataSearchViewModel`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::SshProxyDataSearchViewModel`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SecretSessionsServiceGetSshProxyDataError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get the SSH proxy session data as an attached file
pub async fn secret_sessions_service_get_ssh_proxy_data_as_file(configuration: &configuration::Configuration, audit_secret_id: Option<i32>, filter_type: Option<&str>, search_term: Option<&str>, secret_session_id: Option<i32>, secret_session_key: Option<&str>, session_guid: Option<&str>) -> Result<serde_json::Value, Error<SecretSessionsServiceGetSshProxyDataAsFileError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_audit_secret_id = audit_secret_id;
    let p_query_filter_type = filter_type;
    let p_query_search_term = search_term;
    let p_query_secret_session_id = secret_session_id;
    let p_query_secret_session_key = secret_session_key;
    let p_query_session_guid = session_guid;

    let uri_str = format!("{}/v1/recorded-sessions/ssh-session-file", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_audit_secret_id {
        req_builder = req_builder.query(&[("auditSecretId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filter_type {
        req_builder = req_builder.query(&[("filterType", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_search_term {
        req_builder = req_builder.query(&[("searchTerm", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_secret_session_id {
        req_builder = req_builder.query(&[("secretSessionId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_secret_session_key {
        req_builder = req_builder.query(&[("secretSessionKey", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_session_guid {
        req_builder = req_builder.query(&[("sessionGuid", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `serde_json::Value`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `serde_json::Value`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SecretSessionsServiceGetSshProxyDataAsFileError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get the summary for a recorded session
pub async fn secret_sessions_service_get_summary(configuration: &configuration::Configuration, id: &str) -> Result<models::SecretSessionSummary, Error<SecretSessionsServiceGetSummaryError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/v1/recorded-sessions/{id}/summary", configuration.base_path, id=crate::apis::urlencode(p_path_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::SecretSessionSummary`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::SecretSessionSummary`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SecretSessionsServiceGetSummaryError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Issues a request for the immediate processing of a session video
pub async fn secret_sessions_service_process_session(configuration: &configuration::Configuration, id: &str) -> Result<(), Error<SecretSessionsServiceProcessSessionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/v1/recorded-sessions/{id}/request-processing", configuration.base_path, id=crate::apis::urlencode(p_path_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<SecretSessionsServiceProcessSessionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get the points of interest for a recorded session
pub async fn secret_sessions_service_search_points_of_interest(configuration: &configuration::Configuration, id: &str, filter_search_text: Option<&str>, skip: Option<i32>, sort_by_left_square_bracket_0_right_square_bracket__direction: Option<&str>, sort_by_left_square_bracket_0_right_square_bracket__name: Option<&str>, sort_by_left_square_bracket_0_right_square_bracket__priority: Option<i32>, take: Option<i32>) -> Result<models::PagingOfSecretSessionPointOfInterestModel, Error<SecretSessionsServiceSearchPointsOfInterestError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_query_filter_search_text = filter_search_text;
    let p_query_skip = skip;
    let p_query_sort_by_left_square_bracket_0_right_square_bracket__direction = sort_by_left_square_bracket_0_right_square_bracket__direction;
    let p_query_sort_by_left_square_bracket_0_right_square_bracket__name = sort_by_left_square_bracket_0_right_square_bracket__name;
    let p_query_sort_by_left_square_bracket_0_right_square_bracket__priority = sort_by_left_square_bracket_0_right_square_bracket__priority;
    let p_query_take = take;

    let uri_str = format!("{}/v1/recorded-sessions/{id}/points-of-interest", configuration.base_path, id=crate::apis::urlencode(p_path_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_filter_search_text {
        req_builder = req_builder.query(&[("filter.searchText", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_skip {
        req_builder = req_builder.query(&[("skip", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort_by_left_square_bracket_0_right_square_bracket__direction {
        req_builder = req_builder.query(&[("sortBy[0].direction", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort_by_left_square_bracket_0_right_square_bracket__name {
        req_builder = req_builder.query(&[("sortBy[0].name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort_by_left_square_bracket_0_right_square_bracket__priority {
        req_builder = req_builder.query(&[("sortBy[0].priority", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_take {
        req_builder = req_builder.query(&[("take", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PagingOfSecretSessionPointOfInterestModel`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PagingOfSecretSessionPointOfInterestModel`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SecretSessionsServiceSearchPointsOfInterestError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get the points of interest summary for a recorded session
pub async fn secret_sessions_service_search_points_of_interest_summary(configuration: &configuration::Configuration, id: &str, filter_search_text: Option<&str>, skip: Option<i32>, sort_by_left_square_bracket_0_right_square_bracket__direction: Option<&str>, sort_by_left_square_bracket_0_right_square_bracket__name: Option<&str>, sort_by_left_square_bracket_0_right_square_bracket__priority: Option<i32>, take: Option<i32>) -> Result<models::PagingOfISecretSessionPointOfInterestSummaryModel, Error<SecretSessionsServiceSearchPointsOfInterestSummaryError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_query_filter_search_text = filter_search_text;
    let p_query_skip = skip;
    let p_query_sort_by_left_square_bracket_0_right_square_bracket__direction = sort_by_left_square_bracket_0_right_square_bracket__direction;
    let p_query_sort_by_left_square_bracket_0_right_square_bracket__name = sort_by_left_square_bracket_0_right_square_bracket__name;
    let p_query_sort_by_left_square_bracket_0_right_square_bracket__priority = sort_by_left_square_bracket_0_right_square_bracket__priority;
    let p_query_take = take;

    let uri_str = format!("{}/v1/recorded-sessions/{id}/points-of-interest-summary", configuration.base_path, id=crate::apis::urlencode(p_path_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_filter_search_text {
        req_builder = req_builder.query(&[("filter.searchText", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_skip {
        req_builder = req_builder.query(&[("skip", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort_by_left_square_bracket_0_right_square_bracket__direction {
        req_builder = req_builder.query(&[("sortBy[0].direction", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort_by_left_square_bracket_0_right_square_bracket__name {
        req_builder = req_builder.query(&[("sortBy[0].name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort_by_left_square_bracket_0_right_square_bracket__priority {
        req_builder = req_builder.query(&[("sortBy[0].priority", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_take {
        req_builder = req_builder.query(&[("take", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PagingOfISecretSessionPointOfInterestSummaryModel`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PagingOfISecretSessionPointOfInterestSummaryModel`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SecretSessionsServiceSearchPointsOfInterestSummaryError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Search, filter, sort, and page recorded sessions
pub async fn secret_sessions_service_search_sessions(configuration: &configuration::Configuration, filter_active: Option<bool>, filter_date_range: Option<&str>, filter_end_date: Option<String>, filter_end_time: Option<&str>, filter_excluded_applications: Option<Vec<String>>, filter_folder_id: Option<i32>, filter_group_ids: Option<Vec<i32>>, filter_has_error: Option<bool>, filter_include_non_secret_server_sessions: Option<bool>, filter_include_only_launched_successfully: Option<bool>, filter_include_restricted: Option<bool>, filter_include_sub_folders: Option<bool>, filter_launcher_type_id: Option<i32>, filter_search_text: Option<&str>, filter_search_types: Option<Vec<String>>, filter_secret_ids: Option<Vec<i32>>, filter_site_id: Option<i32>, filter_start_date: Option<String>, filter_start_time: Option<&str>, filter_user_ids: Option<Vec<i32>>, skip: Option<i32>, sort_by_left_square_bracket_0_right_square_bracket__direction: Option<&str>, sort_by_left_square_bracket_0_right_square_bracket__name: Option<&str>, sort_by_left_square_bracket_0_right_square_bracket__priority: Option<i32>, take: Option<i32>) -> Result<models::PagingOfSecretSessionSummary, Error<SecretSessionsServiceSearchSessionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_filter_active = filter_active;
    let p_query_filter_date_range = filter_date_range;
    let p_query_filter_end_date = filter_end_date;
    let p_query_filter_end_time = filter_end_time;
    let p_query_filter_excluded_applications = filter_excluded_applications;
    let p_query_filter_folder_id = filter_folder_id;
    let p_query_filter_group_ids = filter_group_ids;
    let p_query_filter_has_error = filter_has_error;
    let p_query_filter_include_non_secret_server_sessions = filter_include_non_secret_server_sessions;
    let p_query_filter_include_only_launched_successfully = filter_include_only_launched_successfully;
    let p_query_filter_include_restricted = filter_include_restricted;
    let p_query_filter_include_sub_folders = filter_include_sub_folders;
    let p_query_filter_launcher_type_id = filter_launcher_type_id;
    let p_query_filter_search_text = filter_search_text;
    let p_query_filter_search_types = filter_search_types;
    let p_query_filter_secret_ids = filter_secret_ids;
    let p_query_filter_site_id = filter_site_id;
    let p_query_filter_start_date = filter_start_date;
    let p_query_filter_start_time = filter_start_time;
    let p_query_filter_user_ids = filter_user_ids;
    let p_query_skip = skip;
    let p_query_sort_by_left_square_bracket_0_right_square_bracket__direction = sort_by_left_square_bracket_0_right_square_bracket__direction;
    let p_query_sort_by_left_square_bracket_0_right_square_bracket__name = sort_by_left_square_bracket_0_right_square_bracket__name;
    let p_query_sort_by_left_square_bracket_0_right_square_bracket__priority = sort_by_left_square_bracket_0_right_square_bracket__priority;
    let p_query_take = take;

    let uri_str = format!("{}/v1/recorded-sessions", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_filter_active {
        req_builder = req_builder.query(&[("filter.active", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filter_date_range {
        req_builder = req_builder.query(&[("filter.dateRange", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filter_end_date {
        req_builder = req_builder.query(&[("filter.endDate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filter_end_time {
        req_builder = req_builder.query(&[("filter.endTime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filter_excluded_applications {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("filter.excludedApplications".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("filter.excludedApplications", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_filter_folder_id {
        req_builder = req_builder.query(&[("filter.folderId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filter_group_ids {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("filter.groupIds".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("filter.groupIds", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_filter_has_error {
        req_builder = req_builder.query(&[("filter.hasError", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filter_include_non_secret_server_sessions {
        req_builder = req_builder.query(&[("filter.includeNonSecretServerSessions", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filter_include_only_launched_successfully {
        req_builder = req_builder.query(&[("filter.includeOnlyLaunchedSuccessfully", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filter_include_restricted {
        req_builder = req_builder.query(&[("filter.includeRestricted", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filter_include_sub_folders {
        req_builder = req_builder.query(&[("filter.includeSubFolders", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filter_launcher_type_id {
        req_builder = req_builder.query(&[("filter.launcherTypeId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filter_search_text {
        req_builder = req_builder.query(&[("filter.searchText", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filter_search_types {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("filter.searchTypes".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("filter.searchTypes", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_filter_secret_ids {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("filter.secretIds".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("filter.secretIds", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_filter_site_id {
        req_builder = req_builder.query(&[("filter.siteId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filter_start_date {
        req_builder = req_builder.query(&[("filter.startDate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filter_start_time {
        req_builder = req_builder.query(&[("filter.startTime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filter_user_ids {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("filter.userIds".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("filter.userIds", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_skip {
        req_builder = req_builder.query(&[("skip", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort_by_left_square_bracket_0_right_square_bracket__direction {
        req_builder = req_builder.query(&[("sortBy[0].direction", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort_by_left_square_bracket_0_right_square_bracket__name {
        req_builder = req_builder.query(&[("sortBy[0].name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort_by_left_square_bracket_0_right_square_bracket__priority {
        req_builder = req_builder.query(&[("sortBy[0].priority", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_take {
        req_builder = req_builder.query(&[("take", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PagingOfSecretSessionSummary`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PagingOfSecretSessionSummary`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SecretSessionsServiceSearchSessionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

