/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccessRequestState : The Status of the request
/// The Status of the request
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccessRequestState {
    #[serde(rename = "WaitingForRequest")]
    WaitingForRequest,
    #[serde(rename = "Pending")]
    Pending,
    #[serde(rename = "Approved")]
    Approved,
    #[serde(rename = "Denied")]
    Denied,
    #[serde(rename = "Canceled")]
    Canceled,
    #[serde(rename = "Expired")]
    Expired,

}

impl std::fmt::Display for AccessRequestState {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::WaitingForRequest => write!(f, "WaitingForRequest"),
            Self::Pending => write!(f, "Pending"),
            Self::Approved => write!(f, "Approved"),
            Self::Denied => write!(f, "Denied"),
            Self::Canceled => write!(f, "Canceled"),
            Self::Expired => write!(f, "Expired"),
        }
    }
}

impl Default for AccessRequestState {
    fn default() -> AccessRequestState {
        Self::WaitingForRequest
    }
}

