/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AlertNotificationStatus : Type
/// Type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AlertNotificationStatus {
    #[serde(rename = "Normal")]
    Normal,
    #[serde(rename = "Critical")]
    Critical,
    #[serde(rename = "RequiresInteraction")]
    RequiresInteraction,

}

impl std::fmt::Display for AlertNotificationStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Normal => write!(f, "Normal"),
            Self::Critical => write!(f, "Critical"),
            Self::RequiresInteraction => write!(f, "RequiresInteraction"),
        }
    }
}

impl Default for AlertNotificationStatus {
    fn default() -> AlertNotificationStatus {
        Self::Normal
    }
}

