/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AppClientUpdateArgs : App client update options
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppClientUpdateArgs {
    /// App client ID. Must match ID in path
    #[serde(rename = "id")]
    pub id: i32,
    /// Authorized redirect URI for this app client
    #[serde(rename = "redirectUri")]
    pub redirect_uri: String,
}

impl AppClientUpdateArgs {
    /// App client update options
    pub fn new(id: i32, redirect_uri: String) -> AppClientUpdateArgs {
        AppClientUpdateArgs {
            id,
            redirect_uri,
        }
    }
}

