/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzureServiceBusTransportType : Azure Service Bus Transport Type
/// Azure Service Bus Transport Type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AzureServiceBusTransportType {
    #[serde(rename = "Amqp")]
    Amqp,
    #[serde(rename = "AmqpWebSockets")]
    AmqpWebSockets,

}

impl std::fmt::Display for AzureServiceBusTransportType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Amqp => write!(f, "Amqp"),
            Self::AmqpWebSockets => write!(f, "AmqpWebSockets"),
        }
    }
}

impl Default for AzureServiceBusTransportType {
    fn default() -> AzureServiceBusTransportType {
        Self::Amqp
    }
}

