/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BadRequestResponse : Response object for invalid requests
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BadRequestResponse {
    /// Error message
    #[serde(rename = "message")]
    pub message: String,
    /// Error message detail
    #[serde(rename = "messageDetail", skip_serializing_if = "Option::is_none")]
    pub message_detail: Option<String>,
    /// Error message code
    #[serde(rename = "errorCode", skip_serializing_if = "Option::is_none")]
    pub error_code: Option<String>,
    /// An object describing validation errors
    #[serde(rename = "modelState", skip_serializing_if = "Option::is_none")]
    pub model_state: Option<serde_json::Value>,
}

impl BadRequestResponse {
    /// Response object for invalid requests
    pub fn new(message: String) -> BadRequestResponse {
        BadRequestResponse {
            message,
            message_detail: None,
            error_code: None,
            model_state: None,
        }
    }
}

