/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BlocklistSecretPolicySummaryModel : Query results
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlocklistSecretPolicySummaryModel {
    /// The Id of the Secret Policy
    #[serde(rename = "secretPolicyId", skip_serializing_if = "Option::is_none")]
    pub secret_policy_id: Option<i32>,
    /// The Name of the Secret Policy
    #[serde(rename = "secretPolicyName", skip_serializing_if = "Option::is_none")]
    pub secret_policy_name: Option<String>,
}

impl BlocklistSecretPolicySummaryModel {
    /// Query results
    pub fn new() -> BlocklistSecretPolicySummaryModel {
        BlocklistSecretPolicySummaryModel {
            secret_policy_id: None,
            secret_policy_name: None,
        }
    }
}

