/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CategorizedListItemSingleCreateArgs : Single List Option Create Argument
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CategorizedListItemSingleCreateArgs {
    #[serde(rename = "option", skip_serializing_if = "Option::is_none")]
    pub option: Option<Box<models::CategorizedListItemCreateModel>>,
}

impl CategorizedListItemSingleCreateArgs {
    /// Single List Option Create Argument
    pub fn new() -> CategorizedListItemSingleCreateArgs {
        CategorizedListItemSingleCreateArgs {
            option: None,
        }
    }
}

