/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfigurationLoginTwoFactorModel : Two Factor Login Configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigurationLoginTwoFactorModel {
    /// When this option is checked, the user will only have to provide their two factor authentication information once in that browser for set time. This is done by setting an encrypted cookie on the browser.  The cookie will no longer be valid when the Two Factor Remember Me Duration has expired
    #[serde(rename = "allowTwoFactorRememberMe", skip_serializing_if = "Option::is_none")]
    pub allow_two_factor_remember_me: Option<bool>,
    #[serde(rename = "duo", skip_serializing_if = "Option::is_none")]
    pub duo: Option<Box<models::ConfigurationLoginTwoFactorDuoModel>>,
    #[serde(rename = "openIdConnect", skip_serializing_if = "Option::is_none")]
    pub open_id_connect: Option<Box<models::ConfigurationLoginTwoFactorOpenIdConnectModel>>,
    #[serde(rename = "radius", skip_serializing_if = "Option::is_none")]
    pub radius: Option<Box<models::ConfigurationLoginTwoFactorRadiusModel>>,
    /// Require Two Factor For Web Login
    #[serde(rename = "requireTwoFactorForWebLogin", skip_serializing_if = "Option::is_none")]
    pub require_two_factor_for_web_login: Option<bool>,
    /// Require Two Factor For Web Services
    #[serde(rename = "requireTwoFactorForWebServices", skip_serializing_if = "Option::is_none")]
    pub require_two_factor_for_web_services: Option<bool>,
    /// The number of days that you will not be reprompted for 2FA
    #[serde(rename = "twoFactorRememberMeTimeOutDays", skip_serializing_if = "Option::is_none")]
    pub two_factor_remember_me_time_out_days: Option<i32>,
}

impl ConfigurationLoginTwoFactorModel {
    /// Two Factor Login Configuration
    pub fn new() -> ConfigurationLoginTwoFactorModel {
        ConfigurationLoginTwoFactorModel {
            allow_two_factor_remember_me: None,
            duo: None,
            open_id_connect: None,
            radius: None,
            require_two_factor_for_web_login: None,
            require_two_factor_for_web_services: None,
            two_factor_remember_me_time_out_days: None,
        }
    }
}

