/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfigurationSamlModel : SAML configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigurationSamlModel {
    /// Enable SAML authentication
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Enable legacy SingleLogout
    #[serde(rename = "enableLegacySLO", skip_serializing_if = "Option::is_none")]
    pub enable_legacy_slo: Option<bool>,
    /// List of Identity Providers
    #[serde(rename = "identityProviders", skip_serializing_if = "Option::is_none")]
    pub identity_providers: Option<Vec<models::ConfigurationSamlIdentityProviderModel>>,
    /// Optional AttributeName to use for matching a Secret Server user.
    #[serde(rename = "legacyUsernameAttribute", skip_serializing_if = "Option::is_none")]
    pub legacy_username_attribute: Option<String>,
    /// The Service Provider Certificate. Base64 encoded
    #[serde(rename = "serviceProviderCertificate", skip_serializing_if = "Option::is_none")]
    pub service_provider_certificate: Option<String>,
    /// The expiration date of the Service Provider Certificate
    #[serde(rename = "serviceProviderCertificateExpirationDateString", skip_serializing_if = "Option::is_none")]
    pub service_provider_certificate_expiration_date_string: Option<String>,
    /// The friendly name of the Service Provider Certificate
    #[serde(rename = "serviceProviderCertificateFriendlyName", skip_serializing_if = "Option::is_none")]
    pub service_provider_certificate_friendly_name: Option<String>,
    /// The password for the Service Provider Certificate
    #[serde(rename = "serviceProviderCertificatePassword", skip_serializing_if = "Option::is_none")]
    pub service_provider_certificate_password: Option<String>,
    /// The subject of the Service Provider Certificate
    #[serde(rename = "serviceProviderCertificateSubject", skip_serializing_if = "Option::is_none")]
    pub service_provider_certificate_subject: Option<String>,
    /// The thumbprint of the Service Provider Certificate
    #[serde(rename = "serviceProviderCertificateThumbprint", skip_serializing_if = "Option::is_none")]
    pub service_provider_certificate_thumbprint: Option<String>,
    /// The name of the Service Provider
    #[serde(rename = "serviceProviderName", skip_serializing_if = "Option::is_none")]
    pub service_provider_name: Option<String>,
    /// Use Legacy SAML
    #[serde(rename = "useLegacy", skip_serializing_if = "Option::is_none")]
    pub use_legacy: Option<bool>,
}

impl ConfigurationSamlModel {
    /// SAML configuration
    pub fn new() -> ConfigurationSamlModel {
        ConfigurationSamlModel {
            enabled: None,
            enable_legacy_slo: None,
            identity_providers: None,
            legacy_username_attribute: None,
            service_provider_certificate: None,
            service_provider_certificate_expiration_date_string: None,
            service_provider_certificate_friendly_name: None,
            service_provider_certificate_password: None,
            service_provider_certificate_subject: None,
            service_provider_certificate_thumbprint: None,
            service_provider_name: None,
            use_legacy: None,
        }
    }
}

