/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfigurationPermissionOptionsUpdateModel : Configuration Permission Options
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigurationPermissionOptionsUpdateModel {
    #[serde(rename = "allowDuplicateSecretNames", skip_serializing_if = "Option::is_none")]
    pub allow_duplicate_secret_names: Option<Box<models::UpdateFieldValueOfBoolean>>,
    #[serde(rename = "allowViewUserToRetrieveAutoChangeNextPassword", skip_serializing_if = "Option::is_none")]
    pub allow_view_user_to_retrieve_auto_change_next_password: Option<Box<models::UpdateFieldValueOfOptionalBoolean>>,
    #[serde(rename = "defaultSecretPermissions", skip_serializing_if = "Option::is_none")]
    pub default_secret_permissions: Option<Box<models::UpdateFieldValueOfDefaultSecretPermissionsType>>,
    #[serde(rename = "enableApprovalFromEmail", skip_serializing_if = "Option::is_none")]
    pub enable_approval_from_email: Option<Box<models::UpdateFieldValueOfOptionalBoolean>>,
    #[serde(rename = "forceSecretApproval", skip_serializing_if = "Option::is_none")]
    pub force_secret_approval: Option<Box<models::UpdateFieldValueOfOptionalForceSecretApprovalType>>,
}

impl ConfigurationPermissionOptionsUpdateModel {
    /// Configuration Permission Options
    pub fn new() -> ConfigurationPermissionOptionsUpdateModel {
        ConfigurationPermissionOptionsUpdateModel {
            allow_duplicate_secret_names: None,
            allow_view_user_to_retrieve_auto_change_next_password: None,
            default_secret_permissions: None,
            enable_approval_from_email: None,
            force_secret_approval: None,
        }
    }
}

