/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfigurationPermissionOptionsModel : Configuration Permission Options
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigurationPermissionOptionsModel {
    /// Allow Secrets to have the same name in the same folder
    #[serde(rename = "allowDuplicateSecretNames", skip_serializing_if = "Option::is_none")]
    pub allow_duplicate_secret_names: Option<bool>,
    /// Users that only have secret view can see the next password
    #[serde(rename = "allowViewUserToRetrieveAutoChangeNextPassword", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub allow_view_user_to_retrieve_auto_change_next_password: Option<Option<bool>>,
    #[serde(rename = "defaultSecretPermissions", skip_serializing_if = "Option::is_none")]
    pub default_secret_permissions: Option<models::DefaultSecretPermissionsType>,
    /// Allow approval from email
    #[serde(rename = "enableApprovalFromEmail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub enable_approval_from_email: Option<Option<bool>>,
    /// Require approval for secrets
    #[serde(rename = "forceSecretApproval", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub force_secret_approval: Option<Option<String>>,
}

impl ConfigurationPermissionOptionsModel {
    /// Configuration Permission Options
    pub fn new() -> ConfigurationPermissionOptionsModel {
        ConfigurationPermissionOptionsModel {
            allow_duplicate_secret_names: None,
            allow_view_user_to_retrieve_auto_change_next_password: None,
            default_secret_permissions: None,
            enable_approval_from_email: None,
            force_secret_approval: None,
        }
    }
}

