/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConvertTemplateInfoModel : Define which secrets are being converted to what template type
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConvertTemplateInfoModel {
    /// What secret template are you converting to
    #[serde(rename = "destinationTemplateId", skip_serializing_if = "Option::is_none")]
    pub destination_template_id: Option<i32>,
    /// Which secret IDs are being converted
    #[serde(rename = "secretIds", skip_serializing_if = "Option::is_none")]
    pub secret_ids: Option<Vec<i32>>,
}

impl ConvertTemplateInfoModel {
    /// Define which secrets are being converted to what template type
    pub fn new() -> ConvertTemplateInfoModel {
        ConvertTemplateInfoModel {
            destination_template_id: None,
            secret_ids: None,
        }
    }
}

