/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomLauncherModel : CustomLauncher
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomLauncherModel {
    /// The additional process to record if record multiple windows is set to true
    #[serde(rename = "additionalProcessesToRecord", skip_serializing_if = "Option::is_none")]
    pub additional_processes_to_record: Option<String>,
    /// The batch file data
    #[serde(rename = "batchFileData", skip_serializing_if = "Option::is_none")]
    pub batch_file_data: Option<std::path::PathBuf>,
    /// The batch file id
    #[serde(rename = "batchFileId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub batch_file_id: Option<Option<i32>>,
    /// The batch file name
    #[serde(rename = "batchFileName", skip_serializing_if = "Option::is_none")]
    pub batch_file_name: Option<String>,
    /// Denotes a group of characters to escape
    #[serde(rename = "charactersToEscape", skip_serializing_if = "Option::is_none")]
    pub characters_to_escape: Option<String>,
    /// The ID of the child launcher associated to this launcher
    #[serde(rename = "childLauncherId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub child_launcher_id: Option<Option<i32>>,
    /// Denotes an escape character
    #[serde(rename = "escapeCharacter", skip_serializing_if = "Option::is_none")]
    pub escape_character: Option<String>,
    /// Determines whether to launch as secret credentials
    #[serde(rename = "launchAsSecretCredentials", skip_serializing_if = "Option::is_none")]
    pub launch_as_secret_credentials: Option<bool>,
    /// Determines whether to load user profile if launch as secret credentials is set to true
    #[serde(rename = "loadUserProfile", skip_serializing_if = "Option::is_none")]
    pub load_user_profile: Option<bool>,
    /// the updated mac process arguments
    #[serde(rename = "macProcessArguments", skip_serializing_if = "Option::is_none")]
    pub mac_process_arguments: Option<String>,
    /// The updated mac process name
    #[serde(rename = "macProcessName", skip_serializing_if = "Option::is_none")]
    pub mac_process_name: Option<String>,
    /// Determines whether to wrap parameters in quotes
    #[serde(rename = "overrideDisallowAdditionalParametersInQuotes", skip_serializing_if = "Option::is_none")]
    pub override_disallow_additional_parameters_in_quotes: Option<bool>,
    /// Determines whether to preserve ssh client
    #[serde(rename = "preserveSSHClientProcess", skip_serializing_if = "Option::is_none")]
    pub preserve_ssh_client_process: Option<bool>,
    /// The process arguments
    #[serde(rename = "processArguments", skip_serializing_if = "Option::is_none")]
    pub process_arguments: Option<String>,
    /// The process name
    #[serde(rename = "processName", skip_serializing_if = "Option::is_none")]
    pub process_name: Option<String>,
    /// The rds credentials secret ID
    #[serde(rename = "rdsCredentialsSecretId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rds_credentials_secret_id: Option<Option<i32>>,
    /// The rds credentials secret name
    #[serde(rename = "rdsCredentialsSecretName", skip_serializing_if = "Option::is_none")]
    pub rds_credentials_secret_name: Option<String>,
    /// The rds server hostname
    #[serde(rename = "rdsServerHostname", skip_serializing_if = "Option::is_none")]
    pub rds_server_hostname: Option<String>,
    /// The rds server port
    #[serde(rename = "rdsServerPort", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rds_server_port: Option<Option<i32>>,
    /// Determines whether to record keystrokes
    #[serde(rename = "recordKeystrokes", skip_serializing_if = "Option::is_none")]
    pub record_keystrokes: Option<bool>,
    /// Determines whether to record multiple windows
    #[serde(rename = "recordMultipleWindows", skip_serializing_if = "Option::is_none")]
    pub record_multiple_windows: Option<bool>,
    /// The run type id for the launcher
    #[serde(rename = "runType", skip_serializing_if = "Option::is_none")]
    pub run_type: Option<i32>,
    /// The shell script data
    #[serde(rename = "shellScriptData", skip_serializing_if = "Option::is_none")]
    pub shell_script_data: Option<std::path::PathBuf>,
    /// The shell script id
    #[serde(rename = "shellScriptId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub shell_script_id: Option<Option<i32>>,
    /// The shell script name
    #[serde(rename = "shellScriptName", skip_serializing_if = "Option::is_none")]
    pub shell_script_name: Option<String>,
    /// Determines whether to use sftp tunnel to allow multiple data connections
    #[serde(rename = "useSFTPTunnel", skip_serializing_if = "Option::is_none")]
    pub use_sftp_tunnel: Option<bool>,
    /// Determines whether to use shell execute
    #[serde(rename = "useShellExecute", skip_serializing_if = "Option::is_none")]
    pub use_shell_execute: Option<bool>,
    /// Determines whether to us ssh tunnel
    #[serde(rename = "useSSHTunnel", skip_serializing_if = "Option::is_none")]
    pub use_ssh_tunnel: Option<bool>,
}

impl CustomLauncherModel {
    /// CustomLauncher
    pub fn new() -> CustomLauncherModel {
        CustomLauncherModel {
            additional_processes_to_record: None,
            batch_file_data: None,
            batch_file_id: None,
            batch_file_name: None,
            characters_to_escape: None,
            child_launcher_id: None,
            escape_character: None,
            launch_as_secret_credentials: None,
            load_user_profile: None,
            mac_process_arguments: None,
            mac_process_name: None,
            override_disallow_additional_parameters_in_quotes: None,
            preserve_ssh_client_process: None,
            process_arguments: None,
            process_name: None,
            rds_credentials_secret_id: None,
            rds_credentials_secret_name: None,
            rds_server_hostname: None,
            rds_server_port: None,
            record_keystrokes: None,
            record_multiple_windows: None,
            run_type: None,
            shell_script_data: None,
            shell_script_id: None,
            shell_script_name: None,
            use_sftp_tunnel: None,
            use_shell_execute: None,
            use_ssh_tunnel: None,
        }
    }
}

