/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomCommandCreateArgs : CustomCommandCreateArgs
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomCommandCreateArgs {
    /// Command
    #[serde(rename = "command", skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
    /// CommandTypeCode
    #[serde(rename = "commandTypeCode", skip_serializing_if = "Option::is_none")]
    pub command_type_code: Option<i32>,
    /// Comment
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// PasswordTypeId
    #[serde(rename = "passwordTypeId", skip_serializing_if = "Option::is_none")]
    pub password_type_id: Option<i32>,
    /// Pause
    #[serde(rename = "pause", skip_serializing_if = "Option::is_none")]
    pub pause: Option<i32>,
}

impl CustomCommandCreateArgs {
    /// CustomCommandCreateArgs
    pub fn new() -> CustomCommandCreateArgs {
        CustomCommandCreateArgs {
            command: None,
            command_type_code: None,
            comment: None,
            password_type_id: None,
            pause: None,
        }
    }
}

