/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DefaultDiscoverySettingForDisplay : DefaultDiscoverySettingForDisplays
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DefaultDiscoverySettingForDisplay {
    /// DeterminesAuthentication
    #[serde(rename = "determinesAuthentication", skip_serializing_if = "Option::is_none")]
    pub determines_authentication: Option<bool>,
    /// DropDownOptions
    #[serde(rename = "dropDownOptions", skip_serializing_if = "Option::is_none")]
    pub drop_down_options: Option<Vec<models::DropDownOption>>,
    /// DropDownOptionsForDisplay
    #[serde(rename = "dropDownOptionsForDisplay", skip_serializing_if = "Option::is_none")]
    pub drop_down_options_for_display: Option<Vec<models::DropDownOptionForDisplay>>,
    /// Editable
    #[serde(rename = "editable", skip_serializing_if = "Option::is_none")]
    pub editable: Option<bool>,
    /// HasError
    #[serde(rename = "hasError", skip_serializing_if = "Option::is_none")]
    pub has_error: Option<bool>,
    /// Name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// NameForDisplay
    #[serde(rename = "nameForDisplay", skip_serializing_if = "Option::is_none")]
    pub name_for_display: Option<String>,
    /// NameLocalizeKey
    #[serde(rename = "nameLocalizeKey", skip_serializing_if = "Option::is_none")]
    pub name_localize_key: Option<String>,
    /// RegexValidation
    #[serde(rename = "regexValidation", skip_serializing_if = "Option::is_none")]
    pub regex_validation: Option<String>,
    #[serde(rename = "requiredScanTypes", skip_serializing_if = "Option::is_none")]
    pub required_scan_types: Option<Box<models::RequiredScanTypes>>,
    #[serde(rename = "settingDependency", skip_serializing_if = "Option::is_none")]
    pub setting_dependency: Option<Box<models::SettingDependency>>,
    /// TooltipForDisplay
    #[serde(rename = "tooltipForDisplay", skip_serializing_if = "Option::is_none")]
    pub tooltip_for_display: Option<String>,
    /// TooltipLocalizeKey
    #[serde(rename = "tooltipLocalizeKey", skip_serializing_if = "Option::is_none")]
    pub tooltip_localize_key: Option<String>,
    /// Type
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<i32>,
    /// Value
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    /// Visible
    #[serde(rename = "visible", skip_serializing_if = "Option::is_none")]
    pub visible: Option<bool>,
}

impl DefaultDiscoverySettingForDisplay {
    /// DefaultDiscoverySettingForDisplays
    pub fn new() -> DefaultDiscoverySettingForDisplay {
        DefaultDiscoverySettingForDisplay {
            determines_authentication: None,
            drop_down_options: None,
            drop_down_options_for_display: None,
            editable: None,
            has_error: None,
            name: None,
            name_for_display: None,
            name_localize_key: None,
            regex_validation: None,
            required_scan_types: None,
            setting_dependency: None,
            tooltip_for_display: None,
            tooltip_localize_key: None,
            r#type: None,
            value: None,
            visible: None,
        }
    }
}

