/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DevOpsSecretsVaultSyncStatusSummary : Query results
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DevOpsSecretsVaultSyncStatusSummary {
    /// If the mapping is active.
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    /// When the Secret will be pushed next.
    #[serde(rename = "dateAdded", skip_serializing_if = "Option::is_none")]
    pub date_added: Option<String>,
    /// Where to push the Secret to in the Tenant.
    #[serde(rename = "devOpsSecretVaultPath", skip_serializing_if = "Option::is_none")]
    pub dev_ops_secret_vault_path: Option<String>,
    /// ID of the mapping between the Tenant and Secret.
    #[serde(rename = "devOpsSyncMapId", skip_serializing_if = "Option::is_none")]
    pub dev_ops_sync_map_id: Option<i32>,
    /// When the Secret was last pushed.
    #[serde(rename = "lastSyncTime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_sync_time: Option<Option<String>>,
    /// Name of the Secret.
    #[serde(rename = "secretName", skip_serializing_if = "Option::is_none")]
    pub secret_name: Option<String>,
    /// Status of syncing progress.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl DevOpsSecretsVaultSyncStatusSummary {
    /// Query results
    pub fn new() -> DevOpsSecretsVaultSyncStatusSummary {
        DevOpsSecretsVaultSyncStatusSummary {
            active: None,
            date_added: None,
            dev_ops_secret_vault_path: None,
            dev_ops_sync_map_id: None,
            last_sync_time: None,
            secret_name: None,
            status: None,
        }
    }
}

