/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DisasterRecoveryIncomingConfigurationModel : Disaster Recovery Configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DisasterRecoveryIncomingConfigurationModel {
    /// The data replica name given to it by the data source.
    #[serde(rename = "dataReplicaName", skip_serializing_if = "Option::is_none")]
    pub data_replica_name: Option<String>,
    /// Whether data replication is enabled.
    #[serde(rename = "dataReplicationEnabled", skip_serializing_if = "Option::is_none")]
    pub data_replication_enabled: Option<bool>,
    /// The SHA-256 hash of the data source certificate's public key.
    #[serde(rename = "dataSourceCertificatePinningKeyHashSha256", skip_serializing_if = "Option::is_none")]
    pub data_source_certificate_pinning_key_hash_sha256: Option<String>,
    /// The data source key.
    #[serde(rename = "dataSourceKey", skip_serializing_if = "Option::is_none")]
    pub data_source_key: Option<String>,
    /// The data source URL.
    #[serde(rename = "dataSourceUrl", skip_serializing_if = "Option::is_none")]
    pub data_source_url: Option<String>,
    /// Whether this instance of Secret Server is a data replica, a data source, or neither.
    #[serde(rename = "isReplica", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_replica: Option<Option<bool>>,
    /// Whether data replication is currently active.
    #[serde(rename = "isReplicating", skip_serializing_if = "Option::is_none")]
    pub is_replicating: Option<bool>,
    /// The last time data replication ran.
    #[serde(rename = "lastReplicated", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_replicated: Option<Option<String>>,
    /// How frequently data replication will take place on this data replica.
    #[serde(rename = "replicationIntervalMinutes", skip_serializing_if = "Option::is_none")]
    pub replication_interval_minutes: Option<i32>,
    /// Current step in the replication process when currently active
    #[serde(rename = "replicationStatus", skip_serializing_if = "Option::is_none")]
    pub replication_status: Option<String>,
}

impl DisasterRecoveryIncomingConfigurationModel {
    /// Disaster Recovery Configuration
    pub fn new() -> DisasterRecoveryIncomingConfigurationModel {
        DisasterRecoveryIncomingConfigurationModel {
            data_replica_name: None,
            data_replication_enabled: None,
            data_source_certificate_pinning_key_hash_sha256: None,
            data_source_key: None,
            data_source_url: None,
            is_replica: None,
            is_replicating: None,
            last_replicated: None,
            replication_interval_minutes: None,
            replication_status: None,
        }
    }
}

