/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DiscoveryScanTemplateCreateData : Create a scan template model
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscoveryScanTemplateCreateData {
    /// When scantype = 4 the account scan template ID should be specified
    #[serde(rename = "accountScanId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account_scan_id: Option<Option<i32>>,
    /// When true the Fields property can be blank and the scan template will be created with the default fields from the parent
    #[serde(rename = "createDefaultFields", skip_serializing_if = "Option::is_none")]
    pub create_default_fields: Option<bool>,
    /// The mapping and list of fields for this scan template
    #[serde(rename = "fields", skip_serializing_if = "Option::is_none")]
    pub fields: Option<Vec<models::DiscoveryScanTemplateCreateFieldModel>>,
    /// Indicates if this scan template is active
    #[serde(rename = "isActive", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    /// The ID of the parent scan template
    #[serde(rename = "parentScanTemplateId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent_scan_template_id: Option<Option<i32>>,
    /// The name of the scan template
    #[serde(rename = "scanTemplateName", skip_serializing_if = "Option::is_none")]
    pub scan_template_name: Option<String>,
    /// Scan type ID (1, 2, 3, 4)
    #[serde(rename = "scanTypeId", skip_serializing_if = "Option::is_none")]
    pub scan_type_id: Option<i32>,
}

impl DiscoveryScanTemplateCreateData {
    /// Create a scan template model
    pub fn new() -> DiscoveryScanTemplateCreateData {
        DiscoveryScanTemplateCreateData {
            account_scan_id: None,
            create_default_fields: None,
            fields: None,
            is_active: None,
            parent_scan_template_id: None,
            scan_template_name: None,
            scan_type_id: None,
        }
    }
}

