/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DiscoveryScannerDependencyTemplateCreateData : Create a Scanner Dependency Template model
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscoveryScannerDependencyTemplateCreateData {
    /// Indicates if this Dependency Template is active
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    /// The Scan Template ID of the Dependency Template
    #[serde(rename = "scanItemTemplateId", skip_serializing_if = "Option::is_none")]
    pub scan_item_template_id: Option<i32>,
    /// The Dependency Changer ID of the Dependency Template
    #[serde(rename = "secretDependencyChangerId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub secret_dependency_changer_id: Option<Option<i32>>,
    /// The description of the Dependency Template
    #[serde(rename = "secretDependencyTemplateDescription", skip_serializing_if = "Option::is_none")]
    pub secret_dependency_template_description: Option<String>,
    /// The name of the Dependency Template
    #[serde(rename = "secretDependencyTemplateName", skip_serializing_if = "Option::is_none")]
    pub secret_dependency_template_name: Option<String>,
    /// The Dependency Type of the Dependency Template
    #[serde(rename = "secretDependencyTypeId", skip_serializing_if = "Option::is_none")]
    pub secret_dependency_type_id: Option<i32>,
}

impl DiscoveryScannerDependencyTemplateCreateData {
    /// Create a Scanner Dependency Template model
    pub fn new() -> DiscoveryScannerDependencyTemplateCreateData {
        DiscoveryScannerDependencyTemplateCreateData {
            active: None,
            scan_item_template_id: None,
            secret_dependency_changer_id: None,
            secret_dependency_template_description: None,
            secret_dependency_template_name: None,
            secret_dependency_type_id: None,
        }
    }
}

