/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DiscoveryRuleDependencySummary : Discovery Rule Dependency Summary
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscoveryRuleDependencySummary {
    /// Dependency Template Id
    #[serde(rename = "dependencyTemplateId", skip_serializing_if = "Option::is_none")]
    pub dependency_template_id: Option<i32>,
    /// Dependency Template Name
    #[serde(rename = "dependencyTemplateName", skip_serializing_if = "Option::is_none")]
    pub dependency_template_name: Option<String>,
    /// Discovery Source Id
    #[serde(rename = "discoverySourceId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub discovery_source_id: Option<Option<i32>>,
    /// Discovery Source Name
    #[serde(rename = "discoverySourceName", skip_serializing_if = "Option::is_none")]
    pub discovery_source_name: Option<String>,
    /// Is Active
    #[serde(rename = "isActive", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    /// Rule Id
    #[serde(rename = "ruleId", skip_serializing_if = "Option::is_none")]
    pub rule_id: Option<i32>,
    /// Rule Name
    #[serde(rename = "ruleName", skip_serializing_if = "Option::is_none")]
    pub rule_name: Option<String>,
    /// Scan Template Id
    #[serde(rename = "scanTemplateId", skip_serializing_if = "Option::is_none")]
    pub scan_template_id: Option<i32>,
    /// Scan Template Name
    #[serde(rename = "scanTemplateName", skip_serializing_if = "Option::is_none")]
    pub scan_template_name: Option<String>,
    /// Sort Order
    #[serde(rename = "sortOrder", skip_serializing_if = "Option::is_none")]
    pub sort_order: Option<i32>,
}

impl DiscoveryRuleDependencySummary {
    /// Discovery Rule Dependency Summary
    pub fn new() -> DiscoveryRuleDependencySummary {
        DiscoveryRuleDependencySummary {
            dependency_template_id: None,
            dependency_template_name: None,
            discovery_source_id: None,
            discovery_source_name: None,
            is_active: None,
            rule_id: None,
            rule_name: None,
            scan_template_id: None,
            scan_template_name: None,
            sort_order: None,
        }
    }
}

