/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DiscoveryScanTemplateFieldModel : Scan template field
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscoveryScanTemplateFieldModel {
    /// Include this field in the matching to find unique items
    #[serde(rename = "includeInMatch", skip_serializing_if = "Option::is_none")]
    pub include_in_match: Option<bool>,
    /// indicates if this field is active
    #[serde(rename = "isActive", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    /// Indicates if this field is required
    #[serde(rename = "isRequired", skip_serializing_if = "Option::is_none")]
    pub is_required: Option<bool>,
    /// The ID of the parent field
    #[serde(rename = "parentScanItemFieldId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent_scan_item_field_id: Option<Option<i32>>,
    /// The name of the parent field
    #[serde(rename = "parentScanItemFieldName", skip_serializing_if = "Option::is_none")]
    pub parent_scan_item_field_name: Option<String>,
    /// Scan template field ID
    #[serde(rename = "scanItemFieldId", skip_serializing_if = "Option::is_none")]
    pub scan_item_field_id: Option<i32>,
    /// The name of the field
    #[serde(rename = "scanItemFieldName", skip_serializing_if = "Option::is_none")]
    pub scan_item_field_name: Option<String>,
    /// Which scan template does this field belong to
    #[serde(rename = "scanItemTemplateId", skip_serializing_if = "Option::is_none")]
    pub scan_item_template_id: Option<i32>,
    /// The sort order for this field
    #[serde(rename = "sortOrder", skip_serializing_if = "Option::is_none")]
    pub sort_order: Option<i32>,
    /// IS this a system field
    #[serde(rename = "systemField", skip_serializing_if = "Option::is_none")]
    pub system_field: Option<bool>,
}

impl DiscoveryScanTemplateFieldModel {
    /// Scan template field
    pub fn new() -> DiscoveryScanTemplateFieldModel {
        DiscoveryScanTemplateFieldModel {
            include_in_match: None,
            is_active: None,
            is_required: None,
            parent_scan_item_field_id: None,
            parent_scan_item_field_name: None,
            scan_item_field_id: None,
            scan_item_field_name: None,
            scan_item_template_id: None,
            sort_order: None,
            system_field: None,
        }
    }
}

