/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DiscoveryScannerSummary : A Discovery Scanner is what is used in a discovery flow to scan and find things.  All scanners consume one type of scan template (entity) and output scan templates of a different type.  For example, a machine scanner consumes machine scan templates and outputs account scan templates.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscoveryScannerSummary {
    /// The base scanner indicates how the scanner actually executes or performs the scanning
    #[serde(rename = "baseScannerName", skip_serializing_if = "Option::is_none")]
    pub base_scanner_name: Option<String>,
    /// Short description of this scanner
    #[serde(rename = "discoveryItemScannerDescription", skip_serializing_if = "Option::is_none")]
    pub discovery_item_scanner_description: Option<String>,
    /// The localized name of the scanner
    #[serde(rename = "discoveryItemScannerDisplayName", skip_serializing_if = "Option::is_none")]
    pub discovery_item_scanner_display_name: Option<String>,
    /// The unique ID for this scanner
    #[serde(rename = "discoveryItemScannerId", skip_serializing_if = "Option::is_none")]
    pub discovery_item_scanner_id: Option<i32>,
    /// The name of this scanner
    #[serde(rename = "discoveryItemScannerName", skip_serializing_if = "Option::is_none")]
    pub discovery_item_scanner_name: Option<String>,
    /// The type of scanner: 1 = host, 2 = machine, 3 = account, 4 = dependency
    #[serde(rename = "discoveryScanTypeId", skip_serializing_if = "Option::is_none")]
    pub discovery_scan_type_id: Option<i32>,
    /// Localized name of the input scan template
    #[serde(rename = "inputScanItemTemplateDisplayName", skip_serializing_if = "Option::is_none")]
    pub input_scan_item_template_display_name: Option<String>,
    /// The ID of the scan template that this scanner consumes
    #[serde(rename = "inputScanItemTemplateId", skip_serializing_if = "Option::is_none")]
    pub input_scan_item_template_id: Option<i32>,
    /// The name of the scan template that this scanner consumes
    #[serde(rename = "inputScanItemTemplateName", skip_serializing_if = "Option::is_none")]
    pub input_scan_item_template_name: Option<String>,
    /// Whether or not this scanner is active
    #[serde(rename = "isActive", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    /// Localized name of the output scan template
    #[serde(rename = "outputScanItemTemplateDisplayName", skip_serializing_if = "Option::is_none")]
    pub output_scan_item_template_display_name: Option<String>,
    /// The ID of the scan template that this scanner outputs
    #[serde(rename = "outputScanItemTemplateId", skip_serializing_if = "Option::is_none")]
    pub output_scan_item_template_id: Option<i32>,
    /// The name of the scan template that this scanner outputs
    #[serde(rename = "outputScanItemTemplateName", skip_serializing_if = "Option::is_none")]
    pub output_scan_item_template_name: Option<String>,
}

impl DiscoveryScannerSummary {
    /// A Discovery Scanner is what is used in a discovery flow to scan and find things.  All scanners consume one type of scan template (entity) and output scan templates of a different type.  For example, a machine scanner consumes machine scan templates and outputs account scan templates.
    pub fn new() -> DiscoveryScannerSummary {
        DiscoveryScannerSummary {
            base_scanner_name: None,
            discovery_item_scanner_description: None,
            discovery_item_scanner_display_name: None,
            discovery_item_scanner_id: None,
            discovery_item_scanner_name: None,
            discovery_scan_type_id: None,
            input_scan_item_template_display_name: None,
            input_scan_item_template_id: None,
            input_scan_item_template_name: None,
            is_active: None,
            output_scan_item_template_display_name: None,
            output_scan_item_template_id: None,
            output_scan_item_template_name: None,
        }
    }
}

