/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DiscoveryRuleDependencyInfo : Discovery Rule Dependency Info
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscoveryRuleDependencyInfo {
    /// Dependency Templates
    #[serde(rename = "dependencyTemplates", skip_serializing_if = "Option::is_none")]
    pub dependency_templates: Option<Vec<models::DiscoveryDependencyTemplateSummary>>,
    /// Determines whether a Privileged Secret is Required when creating a rule for the given scan template
    #[serde(rename = "isPrivilegedSecretRequired", skip_serializing_if = "Option::is_none")]
    pub is_privileged_secret_required: Option<bool>,
    /// Password Type Ids for Filtering Secrets
    #[serde(rename = "passwordTypeIds", skip_serializing_if = "Option::is_none")]
    pub password_type_ids: Option<Vec<i32>>,
    /// Secret Templates
    #[serde(rename = "secretTemplates", skip_serializing_if = "Option::is_none")]
    pub secret_templates: Option<Vec<models::DiscoveryRuleSecretTemplate>>,
}

impl DiscoveryRuleDependencyInfo {
    /// Discovery Rule Dependency Info
    pub fn new() -> DiscoveryRuleDependencyInfo {
        DiscoveryRuleDependencyInfo {
            dependency_templates: None,
            is_privileged_secret_required: None,
            password_type_ids: None,
            secret_templates: None,
        }
    }
}

