/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DiscoveryDependencyImportModel : The model to import depenencies from Discovery
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscoveryDependencyImportModel {
    /// Should the password be changed on the secret
    #[serde(rename = "changePassword", skip_serializing_if = "Option::is_none")]
    pub change_password: Option<bool>,
    /// A privileged account for the dependency
    #[serde(rename = "dependencyPrivilegedAccountId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub dependency_privileged_account_id: Option<Option<i32>>,
    /// The folder ID to create a a secret
    #[serde(rename = "folderId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub folder_id: Option<Option<i32>>,
    /// The item IDs of dependencies
    #[serde(rename = "itemIds", skip_serializing_if = "Option::is_none")]
    pub item_ids: Option<Vec<i32>>,
    /// A password to update the account to
    #[serde(rename = "nextPassword", skip_serializing_if = "Option::is_none")]
    pub next_password: Option<String>,
    /// The existing password of the account if needed
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// Should a random password be used
    #[serde(rename = "randomPassword", skip_serializing_if = "Option::is_none")]
    pub random_password: Option<bool>,
    /// Should the service be restart on changes
    #[serde(rename = "restartService", skip_serializing_if = "Option::is_none")]
    pub restart_service: Option<bool>,
    /// A template for the dependency
    #[serde(rename = "secretDependencyTemplateId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub secret_dependency_template_id: Option<Option<i32>>,
    /// The tokienized secret name
    #[serde(rename = "secretNameFormat", skip_serializing_if = "Option::is_none")]
    pub secret_name_format: Option<String>,
    /// An RPC privileged account for the secret
    #[serde(rename = "secretPrivilegedAccount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub secret_privileged_account: Option<Option<i32>>,
    /// The secret type to create
    #[serde(rename = "secretTypeId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub secret_type_id: Option<Option<i32>>,
    /// Site ID
    #[serde(rename = "siteId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub site_id: Option<Option<i32>>,
    /// A secret for an SSH key for the dependency
    #[serde(rename = "sshKeySecretId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ssh_key_secret_id: Option<Option<i32>>,
}

impl DiscoveryDependencyImportModel {
    /// The model to import depenencies from Discovery
    pub fn new() -> DiscoveryDependencyImportModel {
        DiscoveryDependencyImportModel {
            change_password: None,
            dependency_privileged_account_id: None,
            folder_id: None,
            item_ids: None,
            next_password: None,
            password: None,
            random_password: None,
            restart_service: None,
            secret_dependency_template_id: None,
            secret_name_format: None,
            secret_privileged_account: None,
            secret_type_id: None,
            site_id: None,
            ssh_key_secret_id: None,
        }
    }
}

