/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DiscoveryRuleDependencyCreateModel : Discovery Rule Dependency Create Model
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscoveryRuleDependencyCreateModel {
    /// Discovery Source Id
    #[serde(rename = "discoverySourceId", skip_serializing_if = "Option::is_none")]
    pub discovery_source_id: Option<i32>,
    /// Organization Unit Id
    #[serde(rename = "organizationUnitId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub organization_unit_id: Option<Option<i32>>,
    /// Privileged Account Secret Id
    #[serde(rename = "privilegedAccountSecretId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub privileged_account_secret_id: Option<Option<i32>>,
    /// Restart Services
    #[serde(rename = "restartServices", skip_serializing_if = "Option::is_none")]
    pub restart_services: Option<bool>,
    /// Rule Name
    #[serde(rename = "ruleName", skip_serializing_if = "Option::is_none")]
    pub rule_name: Option<String>,
    /// Scan Template Id
    #[serde(rename = "scanTemplateId", skip_serializing_if = "Option::is_none")]
    pub scan_template_id: Option<i32>,
    /// Secret Dependency Template Id
    #[serde(rename = "secretDependencyTemplateId", skip_serializing_if = "Option::is_none")]
    pub secret_dependency_template_id: Option<i32>,
    /// Site Id
    #[serde(rename = "siteId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub site_id: Option<Option<i32>>,
}

impl DiscoveryRuleDependencyCreateModel {
    /// Discovery Rule Dependency Create Model
    pub fn new() -> DiscoveryRuleDependencyCreateModel {
        DiscoveryRuleDependencyCreateModel {
            discovery_source_id: None,
            organization_unit_id: None,
            privileged_account_secret_id: None,
            restart_services: None,
            rule_name: None,
            scan_template_id: None,
            secret_dependency_template_id: None,
            site_id: None,
        }
    }
}

