/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DomainDiscoveryScopeModel : A discovery filter to limit discovery to specific OU
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DomainDiscoveryScopeModel {
    /// The Secret Server ID of the discovery soure
    #[serde(rename = "discoverySourceId", skip_serializing_if = "Option::is_none")]
    pub discovery_source_id: Option<i32>,
    /// A list of filter memebers
    #[serde(rename = "filters", skip_serializing_if = "Option::is_none")]
    pub filters: Option<Vec<models::DomainDiscoveryScopeFilterModel>>,
    /// Is the look up table ready for the discovery source
    #[serde(rename = "lookupTableIsReady", skip_serializing_if = "Option::is_none")]
    pub lookup_table_is_ready: Option<bool>,
}

impl DomainDiscoveryScopeModel {
    /// A discovery filter to limit discovery to specific OU
    pub fn new() -> DomainDiscoveryScopeModel {
        DomainDiscoveryScopeModel {
            discovery_source_id: None,
            filters: None,
            lookup_table_is_ready: None,
        }
    }
}

