/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EnableFido2TwoFactorForUsersModel : Data
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnableFido2TwoFactorForUsersModel {
    /// User Ids to set Fido2 Two Factor to enabled.
    #[serde(rename = "userIds", skip_serializing_if = "Option::is_none")]
    pub user_ids: Option<Vec<i32>>,
}

impl EnableFido2TwoFactorForUsersModel {
    /// Data
    pub fn new() -> EnableFido2TwoFactorForUsersModel {
        EnableFido2TwoFactorForUsersModel {
            user_ids: None,
        }
    }
}

