/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EventPipelineFilterMapUpdateModel : Value
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventPipelineFilterMapUpdateModel {
    #[serde(rename = "eventPipelineFilterId", skip_serializing_if = "Option::is_none")]
    pub event_pipeline_filter_id: Option<Box<models::UpdateFieldValueOfInt32>>,
    #[serde(rename = "eventPipelineFilterMapId", skip_serializing_if = "Option::is_none")]
    pub event_pipeline_filter_map_id: Option<Box<models::UpdateFieldValueOfOptionalInt32>>,
    #[serde(rename = "eventPipelineFilterName", skip_serializing_if = "Option::is_none")]
    pub event_pipeline_filter_name: Option<Box<models::UpdateFieldValueOfString>>,
    #[serde(rename = "settings", skip_serializing_if = "Option::is_none")]
    pub settings: Option<Box<models::UpdateFieldValueOfSettingUpdateModelLeftSquareBracketRightSquareBracket>>,
    #[serde(rename = "sortOrder", skip_serializing_if = "Option::is_none")]
    pub sort_order: Option<Box<models::UpdateFieldValueOfInt32>>,
}

impl EventPipelineFilterMapUpdateModel {
    /// Value
    pub fn new() -> EventPipelineFilterMapUpdateModel {
        EventPipelineFilterMapUpdateModel {
            event_pipeline_filter_id: None,
            event_pipeline_filter_map_id: None,
            event_pipeline_filter_name: None,
            settings: None,
            sort_order: None,
        }
    }
}

