/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EventPipelineTaskSettingValueMapModel : Event Pipeline Task Setting Value Map
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventPipelineTaskSettingValueMapModel {
    /// Event Pipeline Task Map Id
    #[serde(rename = "eventPipelineTaskMapId", skip_serializing_if = "Option::is_none")]
    pub event_pipeline_task_map_id: Option<i32>,
    /// Event Pipeline Task Setting Value Map Id
    #[serde(rename = "eventPipelineTaskSettingValueMapId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub event_pipeline_task_setting_value_map_id: Option<Option<i32>>,
    /// Override Default
    #[serde(rename = "overrideDefault", skip_serializing_if = "Option::is_none")]
    pub override_default: Option<bool>,
    #[serde(rename = "setting", skip_serializing_if = "Option::is_none")]
    pub setting: Option<Box<models::SettingForDisplay>>,
    /// Setting Display
    #[serde(rename = "settingDisplay", skip_serializing_if = "Option::is_none")]
    pub setting_display: Option<String>,
    /// Setting Display Value
    #[serde(rename = "settingDisplayValue", skip_serializing_if = "Option::is_none")]
    pub setting_display_value: Option<String>,
    /// Setting Id
    #[serde(rename = "settingId", skip_serializing_if = "Option::is_none")]
    pub setting_id: Option<i32>,
    /// Setting Value
    #[serde(rename = "settingValue", skip_serializing_if = "Option::is_none")]
    pub setting_value: Option<String>,
    /// Whether or not to use the setting's default value.
    #[serde(rename = "usingDefault", skip_serializing_if = "Option::is_none")]
    pub using_default: Option<bool>,
}

impl EventPipelineTaskSettingValueMapModel {
    /// Event Pipeline Task Setting Value Map
    pub fn new() -> EventPipelineTaskSettingValueMapModel {
        EventPipelineTaskSettingValueMapModel {
            event_pipeline_task_map_id: None,
            event_pipeline_task_setting_value_map_id: None,
            override_default: None,
            setting: None,
            setting_display: None,
            setting_display_value: None,
            setting_id: None,
            setting_value: None,
            using_default: None,
        }
    }
}

