/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EventPipelineActivateUpdateArgs : EventPipelineActivateUpdateArgs
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventPipelineActivateUpdateArgs {
    /// Activate
    #[serde(rename = "activate", skip_serializing_if = "Option::is_none")]
    pub activate: Option<bool>,
}

impl EventPipelineActivateUpdateArgs {
    /// EventPipelineActivateUpdateArgs
    pub fn new() -> EventPipelineActivateUpdateArgs {
        EventPipelineActivateUpdateArgs {
            activate: None,
        }
    }
}

