/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EventPipelinePolicyRunActivityViewModel : EventPipelinePolicyRunActivityViewModel[]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventPipelinePolicyRunActivityViewModel {
    /// Duration
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<String>,
    /// EndDateTime
    #[serde(rename = "endDateTime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub end_date_time: Option<Option<String>>,
    /// EventAction
    #[serde(rename = "eventAction", skip_serializing_if = "Option::is_none")]
    pub event_action: Option<String>,
    /// EventEntityType
    #[serde(rename = "eventEntityType", skip_serializing_if = "Option::is_none")]
    pub event_entity_type: Option<String>,
    /// EventPipelineDescription
    #[serde(rename = "eventPipelineDescription", skip_serializing_if = "Option::is_none")]
    pub event_pipeline_description: Option<String>,
    /// EventPipelineId
    #[serde(rename = "eventPipelineId", skip_serializing_if = "Option::is_none")]
    pub event_pipeline_id: Option<i32>,
    /// EventPipelineName
    #[serde(rename = "eventPipelineName", skip_serializing_if = "Option::is_none")]
    pub event_pipeline_name: Option<String>,
    /// EventPipelinePolicyRunId
    #[serde(rename = "eventPipelinePolicyRunId", skip_serializing_if = "Option::is_none")]
    pub event_pipeline_policy_run_id: Option<uuid::Uuid>,
    /// EventPipelineTaskDescription
    #[serde(rename = "eventPipelineTaskDescription", skip_serializing_if = "Option::is_none")]
    pub event_pipeline_task_description: Option<String>,
    /// EventPipelineTaskId
    #[serde(rename = "eventPipelineTaskId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub event_pipeline_task_id: Option<Option<i32>>,
    /// EventPipelineTaskName
    #[serde(rename = "eventPipelineTaskName", skip_serializing_if = "Option::is_none")]
    pub event_pipeline_task_name: Option<String>,
    /// ItemId
    #[serde(rename = "itemId", skip_serializing_if = "Option::is_none")]
    pub item_id: Option<i32>,
    /// ItemName
    #[serde(rename = "itemName", skip_serializing_if = "Option::is_none")]
    pub item_name: Option<String>,
    /// Notes
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    /// QueuedDateTime
    #[serde(rename = "queuedDateTime", skip_serializing_if = "Option::is_none")]
    pub queued_date_time: Option<String>,
    /// RunOrder
    #[serde(rename = "runOrder", skip_serializing_if = "Option::is_none")]
    pub run_order: Option<i32>,
    /// StartDateTime
    #[serde(rename = "startDateTime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub start_date_time: Option<Option<String>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::EventPipelineStatus>,
}

impl EventPipelinePolicyRunActivityViewModel {
    /// EventPipelinePolicyRunActivityViewModel[]
    pub fn new() -> EventPipelinePolicyRunActivityViewModel {
        EventPipelinePolicyRunActivityViewModel {
            duration: None,
            end_date_time: None,
            event_action: None,
            event_entity_type: None,
            event_pipeline_description: None,
            event_pipeline_id: None,
            event_pipeline_name: None,
            event_pipeline_policy_run_id: None,
            event_pipeline_task_description: None,
            event_pipeline_task_id: None,
            event_pipeline_task_name: None,
            item_id: None,
            item_name: None,
            notes: None,
            queued_date_time: None,
            run_order: None,
            start_date_time: None,
            status: None,
        }
    }
}

