/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EventPipelineTriggerSummary : EventPipelineTriggerSummary[]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventPipelineTriggerSummary {
    /// Entity Type Display Name
    #[serde(rename = "entityTypeDisplayName", skip_serializing_if = "Option::is_none")]
    pub entity_type_display_name: Option<String>,
    /// Event Action ID ID
    #[serde(rename = "eventActionId", skip_serializing_if = "Option::is_none")]
    pub event_action_id: Option<i32>,
    /// Event Entity Type ID
    #[serde(rename = "eventEntityTypeId", skip_serializing_if = "Option::is_none")]
    pub event_entity_type_id: Option<i32>,
    /// Event Pipeline ID
    #[serde(rename = "eventPipelineId", skip_serializing_if = "Option::is_none")]
    pub event_pipeline_id: Option<i32>,
    /// Event Pipeline Trigger ID
    #[serde(rename = "eventPipelineTriggerId", skip_serializing_if = "Option::is_none")]
    pub event_pipeline_trigger_id: Option<i32>,
    /// Trigger Display Name
    #[serde(rename = "triggerDisplayName", skip_serializing_if = "Option::is_none")]
    pub trigger_display_name: Option<String>,
}

impl EventPipelineTriggerSummary {
    /// EventPipelineTriggerSummary[]
    pub fn new() -> EventPipelineTriggerSummary {
        EventPipelineTriggerSummary {
            entity_type_display_name: None,
            event_action_id: None,
            event_entity_type_id: None,
            event_pipeline_id: None,
            event_pipeline_trigger_id: None,
            trigger_display_name: None,
        }
    }
}

