/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EventSubscriptionTypeActionModel : The list of actions available for the entity
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventSubscriptionTypeActionModel {
    /// A list of available conditions to apply to the action/entity combination
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<models::EventSubscriptionConditionType>>,
    /// The localized name
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// The ID of the event action
    #[serde(rename = "eventActionId", skip_serializing_if = "Option::is_none")]
    pub event_action_id: Option<i32>,
}

impl EventSubscriptionTypeActionModel {
    /// The list of actions available for the entity
    pub fn new() -> EventSubscriptionTypeActionModel {
        EventSubscriptionTypeActionModel {
            conditions: None,
            display_name: None,
            event_action_id: None,
        }
    }
}

