/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FolderPermissionUpdateArgs : Folder permission update options
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FolderPermissionUpdateArgs {
    /// Allow updating of inherited permissions
    #[serde(rename = "breakInheritance", skip_serializing_if = "Option::is_none")]
    pub break_inheritance: Option<bool>,
    /// Role to grant on the folder (View, Edit, Add Secret, Owner)
    #[serde(rename = "folderAccessRoleName")]
    pub folder_access_role_name: String,
    /// Folder ID
    #[serde(rename = "folderId")]
    pub folder_id: i32,
    /// Folder permission ID. Must match ID in path
    #[serde(rename = "id")]
    pub id: i64,
    /// Role to grant on secrets in the folder (View, Edit, List, Owner, None)
    #[serde(rename = "secretAccessRoleName", skip_serializing_if = "Option::is_none")]
    pub secret_access_role_name: Option<String>,
}

impl FolderPermissionUpdateArgs {
    /// Folder permission update options
    pub fn new(folder_access_role_name: String, folder_id: i32, id: i64) -> FolderPermissionUpdateArgs {
        FolderPermissionUpdateArgs {
            break_inheritance: None,
            folder_access_role_name,
            folder_id,
            id,
            secret_access_role_name: None,
        }
    }
}

