/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FolderPermissionCreateArgs : FolderPermissionCreateArgs
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FolderPermissionCreateArgs {
    /// Allow updating of inherited permissions
    #[serde(rename = "breakInheritance", skip_serializing_if = "Option::is_none")]
    pub break_inheritance: Option<bool>,
    /// Role to grant on the folder (View, Edit, Add Secret, Owner)
    #[serde(rename = "folderAccessRoleName", skip_serializing_if = "Option::is_none")]
    pub folder_access_role_name: Option<String>,
    /// Folder on which to grant permissions
    #[serde(rename = "folderId", skip_serializing_if = "Option::is_none")]
    pub folder_id: Option<i32>,
    /// Group to receive permissions
    #[serde(rename = "groupId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub group_id: Option<Option<i32>>,
    /// Role to grant on secrets in the folder (View, Edit, List, Owner, None)
    #[serde(rename = "secretAccessRoleName", skip_serializing_if = "Option::is_none")]
    pub secret_access_role_name: Option<String>,
    /// User to receive permissions
    #[serde(rename = "userId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Option<i32>>,
}

impl FolderPermissionCreateArgs {
    /// FolderPermissionCreateArgs
    pub fn new() -> FolderPermissionCreateArgs {
        FolderPermissionCreateArgs {
            break_inheritance: None,
            folder_access_role_name: None,
            folder_id: None,
            group_id: None,
            secret_access_role_name: None,
            user_id: None,
        }
    }
}

