/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FolderTemplateModel : Describes the properties of a folder/template association
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FolderTemplateModel {
    /// Whether the template is associated with the folder
    #[serde(rename = "associated", skip_serializing_if = "Option::is_none")]
    pub associated: Option<bool>,
    /// Folder ID
    #[serde(rename = "folderId", skip_serializing_if = "Option::is_none")]
    pub folder_id: Option<i32>,
    /// Template ID
    #[serde(rename = "templateId", skip_serializing_if = "Option::is_none")]
    pub template_id: Option<i32>,
}

impl FolderTemplateModel {
    /// Describes the properties of a folder/template association
    pub fn new() -> FolderTemplateModel {
        FolderTemplateModel {
            associated: None,
            folder_id: None,
            template_id: None,
        }
    }
}

