/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FolderSynchronizationMethodType : Defines what type of folder synchronization to use
/// Defines what type of folder synchronization to use
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FolderSynchronizationMethodType {
    #[serde(rename = "None")]
    None,
    #[serde(rename = "LegacyDatabaseIntegration")]
    LegacyDatabaseIntegration,
    #[serde(rename = "ApiIntegration")]
    ApiIntegration,

}

impl std::fmt::Display for FolderSynchronizationMethodType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "None"),
            Self::LegacyDatabaseIntegration => write!(f, "LegacyDatabaseIntegration"),
            Self::ApiIntegration => write!(f, "ApiIntegration"),
        }
    }
}

impl Default for FolderSynchronizationMethodType {
    fn default() -> FolderSynchronizationMethodType {
        Self::None
    }
}

