/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FolderBasicModel : FolderBasicModel
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FolderBasicModel {
    /// Allowed Templates
    #[serde(rename = "allowedTemplates", skip_serializing_if = "Option::is_none")]
    pub allowed_templates: Option<Vec<i32>>,
    /// Should the folder inherit permissions from the parent folder
    #[serde(rename = "enableInheritPermissions", skip_serializing_if = "Option::is_none")]
    pub enable_inherit_permissions: Option<bool>,
    /// Should the folder inherit the secret policy from the parent folder
    #[serde(rename = "enableInheritSecretPolicy", skip_serializing_if = "Option::is_none")]
    pub enable_inherit_secret_policy: Option<bool>,
    /// The dispay name for the folder
    #[serde(rename = "folderName", skip_serializing_if = "Option::is_none")]
    pub folder_name: Option<String>,
    /// If the user can edit the folder
    #[serde(rename = "hasEdit", skip_serializing_if = "Option::is_none")]
    pub has_edit: Option<bool>,
    /// If the user owns the folder
    #[serde(rename = "hasOwner", skip_serializing_if = "Option::is_none")]
    pub has_owner: Option<bool>,
    /// Whether or not this is a personal folder
    #[serde(rename = "isPersonalFolder", skip_serializing_if = "Option::is_none")]
    pub is_personal_folder: Option<bool>,
    /// The ID of the parent folder
    #[serde(rename = "parentFolderId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent_folder_id: Option<Option<i32>>,
    /// Policy name on the parent folder
    #[serde(rename = "parentFolderPolicyName", skip_serializing_if = "Option::is_none")]
    pub parent_folder_policy_name: Option<String>,
    /// SecretPolicies
    #[serde(rename = "secretPolicies", skip_serializing_if = "Option::is_none")]
    pub secret_policies: Option<Vec<models::SecretPolicyModel>>,
    /// The secret policy ID that is assigned to the folder
    #[serde(rename = "secretPolicy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub secret_policy: Option<Option<i32>>,
    /// Secret Templates
    #[serde(rename = "secretTemplates", skip_serializing_if = "Option::is_none")]
    pub secret_templates: Option<Vec<models::TemplateViewModel>>,
}

impl FolderBasicModel {
    /// FolderBasicModel
    pub fn new() -> FolderBasicModel {
        FolderBasicModel {
            allowed_templates: None,
            enable_inherit_permissions: None,
            enable_inherit_secret_policy: None,
            folder_name: None,
            has_edit: None,
            has_owner: None,
            is_personal_folder: None,
            parent_folder_id: None,
            parent_folder_policy_name: None,
            secret_policies: None,
            secret_policy: None,
            secret_templates: None,
        }
    }
}

