/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ICustomReportParameterValue : DefaultParameterValues
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ICustomReportParameterValue {
    /// Name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// ItemId
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<serde_json::Value>,
    /// ValueDisplayName
    #[serde(rename = "valueDisplayName", skip_serializing_if = "Option::is_none")]
    pub value_display_name: Option<String>,
    /// VariableName
    #[serde(rename = "variableName", skip_serializing_if = "Option::is_none")]
    pub variable_name: Option<String>,
}

impl ICustomReportParameterValue {
    /// DefaultParameterValues
    pub fn new() -> ICustomReportParameterValue {
        ICustomReportParameterValue {
            name: None,
            value: None,
            value_display_name: None,
            variable_name: None,
        }
    }
}

