/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InboxTemplateType : Template Type
/// Template Type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InboxTemplateType {
    #[serde(rename = "Email")]
    Email,
    #[serde(rename = "Slack")]
    Slack,

}

impl std::fmt::Display for InboxTemplateType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Email => write!(f, "Email"),
            Self::Slack => write!(f, "Slack"),
        }
    }
}

impl Default for InboxTemplateType {
    fn default() -> InboxTemplateType {
        Self::Email
    }
}

