/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InboxTemplateCreateModel : Data
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InboxTemplateCreateModel {
    /// TemplateName
    #[serde(rename = "templateName", skip_serializing_if = "Option::is_none")]
    pub template_name: Option<String>,
    #[serde(rename = "templateType", skip_serializing_if = "Option::is_none")]
    pub template_type: Option<models::InboxTemplateType>,
}

impl InboxTemplateCreateModel {
    /// Data
    pub fn new() -> InboxTemplateCreateModel {
        InboxTemplateCreateModel {
            template_name: None,
            template_type: None,
        }
    }
}

