/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InboxTemplateModel : Query results
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InboxTemplateModel {
    /// Is System
    #[serde(rename = "isSystem", skip_serializing_if = "Option::is_none")]
    pub is_system: Option<bool>,
    /// Rules leveraging this Template
    #[serde(rename = "rules", skip_serializing_if = "Option::is_none")]
    pub rules: Option<Vec<models::InboxRuleModel>>,
    /// Inbox Template Id
    #[serde(rename = "templateId", skip_serializing_if = "Option::is_none")]
    pub template_id: Option<i32>,
    /// Inbox Template Name
    #[serde(rename = "templateName", skip_serializing_if = "Option::is_none")]
    pub template_name: Option<String>,
    #[serde(rename = "templateType", skip_serializing_if = "Option::is_none")]
    pub template_type: Option<models::InboxTemplateType>,
}

impl InboxTemplateModel {
    /// Query results
    pub fn new() -> InboxTemplateModel {
        InboxTemplateModel {
            is_system: None,
            rules: None,
            template_id: None,
            template_name: None,
            template_type: None,
        }
    }
}

