/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InboxDataType : InboxDataType
/// InboxDataType
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InboxDataType {
    #[serde(rename = "Integer")]
    Integer,
    #[serde(rename = "DateTime")]
    DateTime,
    #[serde(rename = "String")]
    String,
    #[serde(rename = "Boolean")]
    Boolean,

}

impl std::fmt::Display for InboxDataType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Integer => write!(f, "Integer"),
            Self::DateTime => write!(f, "DateTime"),
            Self::String => write!(f, "String"),
            Self::Boolean => write!(f, "Boolean"),
        }
    }
}

impl Default for InboxDataType {
    fn default() -> InboxDataType {
        Self::Integer
    }
}

