/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JumpboxRouteCreateModel : Data
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JumpboxRouteCreateModel {
    /// Active
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    /// Description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl JumpboxRouteCreateModel {
    /// Data
    pub fn new() -> JumpboxRouteCreateModel {
        JumpboxRouteCreateModel {
            active: None,
            description: None,
            name: None,
        }
    }
}

