/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JumpboxRouteModel : JumpboxRouteModel
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JumpboxRouteModel {
    /// Indicates if the Jumpbox Route is active
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    /// Jumpbox Route Descrition
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Jumpbox Route Id
    #[serde(rename = "jumpboxRouteId", skip_serializing_if = "Option::is_none")]
    pub jumpbox_route_id: Option<uuid::Uuid>,
    /// Array of Jumpbox Route Levels attached to a Jumpbox Route
    #[serde(rename = "jumpboxRouteLevels", skip_serializing_if = "Option::is_none")]
    pub jumpbox_route_levels: Option<Vec<models::JumpboxRouteLevelModel>>,
    /// Jumpbox Route Name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl JumpboxRouteModel {
    /// JumpboxRouteModel
    pub fn new() -> JumpboxRouteModel {
        JumpboxRouteModel {
            active: None,
            description: None,
            jumpbox_route_id: None,
            jumpbox_route_levels: None,
            name: None,
        }
    }
}

