/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JumpboxRouteLevelModel : Array of Jumpbox Route Levels attached to a Jumpbox Route
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JumpboxRouteLevelModel {
    /// Jumpbox Route Id
    #[serde(rename = "jumpboxRouteId", skip_serializing_if = "Option::is_none")]
    pub jumpbox_route_id: Option<uuid::Uuid>,
    /// Jumpbox Route Level Order
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<i32>,
    /// Port Assigned to this Jumpbox Route Level
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,
    /// Secret Id Assigned to this Jumpbox Route Level
    #[serde(rename = "secretId", skip_serializing_if = "Option::is_none")]
    pub secret_id: Option<i32>,
}

impl JumpboxRouteLevelModel {
    /// Array of Jumpbox Route Levels attached to a Jumpbox Route
    pub fn new() -> JumpboxRouteLevelModel {
        JumpboxRouteLevelModel {
            jumpbox_route_id: None,
            order: None,
            port: None,
            secret_id: None,
        }
    }
}

