/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LineEnding : Line ending type
/// Line ending type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LineEnding {
    #[serde(rename = "NewLine")]
    NewLine,
    #[serde(rename = "CarriageReturn")]
    CarriageReturn,
    #[serde(rename = "CarriageReturnNewLine")]
    CarriageReturnNewLine,

}

impl std::fmt::Display for LineEnding {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::NewLine => write!(f, "NewLine"),
            Self::CarriageReturn => write!(f, "CarriageReturn"),
            Self::CarriageReturnNewLine => write!(f, "CarriageReturnNewLine"),
        }
    }
}

impl Default for LineEnding {
    fn default() -> LineEnding {
        Self::NewLine
    }
}

