/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MasterEncryptionKeyRotationStatus : CurrentStatus
/// CurrentStatus
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MasterEncryptionKeyRotationStatus {
    #[serde(rename = "NeverRun")]
    NeverRun,
    #[serde(rename = "RotationRequested")]
    RotationRequested,
    #[serde(rename = "KeyRotationStarted")]
    KeyRotationStarted,
    #[serde(rename = "KeyRotationCompleted")]
    KeyRotationCompleted,
    #[serde(rename = "PendingRestart")]
    PendingRestart,
    #[serde(rename = "MarkDataStarted")]
    MarkDataStarted,
    #[serde(rename = "MarkDataCompleted")]
    MarkDataCompleted,
    #[serde(rename = "DataRotationStarted")]
    DataRotationStarted,
    #[serde(rename = "DataRotationCompleted")]
    DataRotationCompleted,
    #[serde(rename = "SessionDataRotationStarted")]
    SessionDataRotationStarted,
    #[serde(rename = "SessionDataRotationCompleted")]
    SessionDataRotationCompleted,
    #[serde(rename = "ProcessCompletedWithErrorsBeforeRotation")]
    ProcessCompletedWithErrorsBeforeRotation,
    #[serde(rename = "ProcessFailedAfterRotation")]
    ProcessFailedAfterRotation,

}

impl std::fmt::Display for MasterEncryptionKeyRotationStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::NeverRun => write!(f, "NeverRun"),
            Self::RotationRequested => write!(f, "RotationRequested"),
            Self::KeyRotationStarted => write!(f, "KeyRotationStarted"),
            Self::KeyRotationCompleted => write!(f, "KeyRotationCompleted"),
            Self::PendingRestart => write!(f, "PendingRestart"),
            Self::MarkDataStarted => write!(f, "MarkDataStarted"),
            Self::MarkDataCompleted => write!(f, "MarkDataCompleted"),
            Self::DataRotationStarted => write!(f, "DataRotationStarted"),
            Self::DataRotationCompleted => write!(f, "DataRotationCompleted"),
            Self::SessionDataRotationStarted => write!(f, "SessionDataRotationStarted"),
            Self::SessionDataRotationCompleted => write!(f, "SessionDataRotationCompleted"),
            Self::ProcessCompletedWithErrorsBeforeRotation => write!(f, "ProcessCompletedWithErrorsBeforeRotation"),
            Self::ProcessFailedAfterRotation => write!(f, "ProcessFailedAfterRotation"),
        }
    }
}

impl Default for MasterEncryptionKeyRotationStatus {
    fn default() -> MasterEncryptionKeyRotationStatus {
        Self::NeverRun
    }
}

