/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MdiIntegrationConfigurationModel : MDI Integration Configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MdiIntegrationConfigurationModel {
    #[serde(rename = "actions", skip_serializing_if = "Option::is_none")]
    pub actions: Option<Box<models::MdiIntegrationConfigurationActionsModel>>,
    /// The URL used for authorization.
    #[serde(rename = "authorizeUrl", skip_serializing_if = "Option::is_none")]
    pub authorize_url: Option<String>,
    /// Whether MDI integration is enabled.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Synchronization period in hours.
    #[serde(rename = "synchronizationIntervalHours", skip_serializing_if = "Option::is_none")]
    pub synchronization_interval_hours: Option<i32>,
    /// The last time the sync operation completed.
    #[serde(rename = "syncLastCompleteDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sync_last_complete_date: Option<Option<String>>,
    /// The last time the sync operation was started.
    #[serde(rename = "syncLastStartDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sync_last_start_date: Option<Option<String>>,
    /// Entra ID Tenant identifier
    #[serde(rename = "tenantId", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<String>,
}

impl MdiIntegrationConfigurationModel {
    /// MDI Integration Configuration
    pub fn new() -> MdiIntegrationConfigurationModel {
        MdiIntegrationConfigurationModel {
            actions: None,
            authorize_url: None,
            enabled: None,
            synchronization_interval_hours: None,
            sync_last_complete_date: None,
            sync_last_start_date: None,
            tenant_id: None,
        }
    }
}

