/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MdiIntegrationSynchronizationStatus : MDI Integration Synchronization Status
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MdiIntegrationSynchronizationStatus {
    /// The date and time that the last synchronization ended.  If a synchronization is currently running this will be empty.
    #[serde(rename = "endDateTime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub end_date_time: Option<Option<String>>,
    /// The number of errors since the last synchronization start time
    #[serde(rename = "errorCount", skip_serializing_if = "Option::is_none")]
    pub error_count: Option<i32>,
    /// Based on last run time duration the percent complete assumes each run takes approximately the same amount of time
    #[serde(rename = "estimatedPercentComplete", skip_serializing_if = "Option::is_none")]
    pub estimated_percent_complete: Option<i32>,
    /// The next time the synchronization is expected to run
    #[serde(rename = "nextSynchronizationDateTime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub next_synchronization_date_time: Option<Option<String>>,
    /// The date and time that the last synchronization started.  This will be empty if a synchronization has never been run.
    #[serde(rename = "startDateTime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub start_date_time: Option<Option<String>>,
}

impl MdiIntegrationSynchronizationStatus {
    /// MDI Integration Synchronization Status
    pub fn new() -> MdiIntegrationSynchronizationStatus {
        MdiIntegrationSynchronizationStatus {
            end_date_time: None,
            error_count: None,
            estimated_percent_complete: None,
            next_synchronization_date_time: None,
            start_date_time: None,
        }
    }
}

