/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PagingOfDiscoverySourceSummaryModel : Specify paging and sorting options for querying records and returning results
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PagingOfDiscoverySourceSummaryModel {
    /// Number of result batches available with current query options
    #[serde(rename = "batchCount", skip_serializing_if = "Option::is_none")]
    pub batch_count: Option<i32>,
    /// Index of current result page
    #[serde(rename = "currentPage", skip_serializing_if = "Option::is_none")]
    pub current_page: Option<i32>,
    /// Whether there are any results in additional pages
    #[serde(rename = "hasNext", skip_serializing_if = "Option::is_none")]
    pub has_next: Option<bool>,
    /// Whether there are any results in previous pages
    #[serde(rename = "hasPrev", skip_serializing_if = "Option::is_none")]
    pub has_prev: Option<bool>,
    /// Correct value of 'skip' for the next page of results
    #[serde(rename = "nextSkip", skip_serializing_if = "Option::is_none")]
    pub next_skip: Option<i32>,
    /// Number of result pages available with current query options
    #[serde(rename = "pageCount", skip_serializing_if = "Option::is_none")]
    pub page_count: Option<i32>,
    /// Correct value of 'skip' for the previous page of results
    #[serde(rename = "prevSkip", skip_serializing_if = "Option::is_none")]
    pub prev_skip: Option<i32>,
    /// Query results
    #[serde(rename = "records", skip_serializing_if = "Option::is_none")]
    pub records: Option<Vec<models::DiscoverySourceSummaryModel>>,
    #[serde(rename = "severity", skip_serializing_if = "Option::is_none")]
    pub severity: Option<models::Severity>,
    /// Number of records to skip before taking results
    #[serde(rename = "skip", skip_serializing_if = "Option::is_none")]
    pub skip: Option<i32>,
    /// List of sort properties
    #[serde(rename = "sortBy", skip_serializing_if = "Option::is_none")]
    pub sort_by: Option<Vec<models::Sort>>,
    /// Whether the query executed successfully
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    /// Maximum number of records to include in results
    #[serde(rename = "take", skip_serializing_if = "Option::is_none")]
    pub take: Option<i32>,
    /// Total number of results available
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
}

impl PagingOfDiscoverySourceSummaryModel {
    /// Specify paging and sorting options for querying records and returning results
    pub fn new() -> PagingOfDiscoverySourceSummaryModel {
        PagingOfDiscoverySourceSummaryModel {
            batch_count: None,
            current_page: None,
            has_next: None,
            has_prev: None,
            next_skip: None,
            page_count: None,
            prev_skip: None,
            records: None,
            severity: None,
            skip: None,
            sort_by: None,
            success: None,
            take: None,
            total: None,
        }
    }
}

