/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PasswordRequirementRuleSummary : Password Requirement Rule Summary
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PasswordRequirementRuleSummary {
    #[serde(rename = "characterSet", skip_serializing_if = "Option::is_none")]
    pub character_set: Option<Box<models::CharacterSetSummary>>,
    /// Minimum Characters Required
    #[serde(rename = "minCharactersRequired", skip_serializing_if = "Option::is_none")]
    pub min_characters_required: Option<i32>,
    /// Password Requirement Id
    #[serde(rename = "passwordRequirementId", skip_serializing_if = "Option::is_none")]
    pub password_requirement_id: Option<i32>,
    /// Password Requirement Rule Id
    #[serde(rename = "passwordRequirementRuleId", skip_serializing_if = "Option::is_none")]
    pub password_requirement_rule_id: Option<i32>,
    #[serde(rename = "passwordRequirementType", skip_serializing_if = "Option::is_none")]
    pub password_requirement_type: Option<models::PasswordRequirementType>,
}

impl PasswordRequirementRuleSummary {
    /// Password Requirement Rule Summary
    pub fn new() -> PasswordRequirementRuleSummary {
        PasswordRequirementRuleSummary {
            character_set: None,
            min_characters_required: None,
            password_requirement_id: None,
            password_requirement_rule_id: None,
            password_requirement_type: None,
        }
    }
}

