/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PbaHistoricalImportViewModel : PBA Historical Import
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PbaHistoricalImportViewModel {
    /// Number Of Events Processed
    #[serde(rename = "numberOfEventsProcessed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub number_of_events_processed: Option<Option<i32>>,
    /// Success
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
}

impl PbaHistoricalImportViewModel {
    /// PBA Historical Import
    pub fn new() -> PbaHistoricalImportViewModel {
        PbaHistoricalImportViewModel {
            number_of_events_processed: None,
            success: None,
        }
    }
}

