/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PbaHistoricalImportStatusResponseMessage : PbaHistoricalImportStatusResponseMessage
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PbaHistoricalImportStatusResponseMessage {
    /// TotalHistoricalEvents
    #[serde(rename = "totalHistoricalEvents", skip_serializing_if = "Option::is_none")]
    pub total_historical_events: Option<i32>,
    /// UnprocessedHistoricalEvents
    #[serde(rename = "unprocessedHistoricalEvents", skip_serializing_if = "Option::is_none")]
    pub unprocessed_historical_events: Option<i32>,
}

impl PbaHistoricalImportStatusResponseMessage {
    /// PbaHistoricalImportStatusResponseMessage
    pub fn new() -> PbaHistoricalImportStatusResponseMessage {
        PbaHistoricalImportStatusResponseMessage {
            total_historical_events: None,
            unprocessed_historical_events: None,
        }
    }
}

