/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PermissionModel : Permissions
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PermissionModel {
    /// RoleId
    #[serde(rename = "roleId", skip_serializing_if = "Option::is_none")]
    pub role_id: Option<i32>,
    /// SecretTypeId
    #[serde(rename = "secretTypeId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub secret_type_id: Option<Option<i32>>,
}

impl PermissionModel {
    /// Permissions
    pub fn new() -> PermissionModel {
        PermissionModel {
            role_id: None,
            secret_type_id: None,
        }
    }
}

