/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PlatformDataMigrationDomainPreCheckSummary : Platform Data Migration Domain Pre-Check Summary
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformDataMigrationDomainPreCheckSummary {
    /// Any Errors from Pre-Check.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::PlatformDataMigrationDomainPreCheckError>>,
    /// Total Domains
    #[serde(rename = "totalDomains", skip_serializing_if = "Option::is_none")]
    pub total_domains: Option<i32>,
    /// Valid Domains
    #[serde(rename = "validDomains", skip_serializing_if = "Option::is_none")]
    pub valid_domains: Option<i32>,
}

impl PlatformDataMigrationDomainPreCheckSummary {
    /// Platform Data Migration Domain Pre-Check Summary
    pub fn new() -> PlatformDataMigrationDomainPreCheckSummary {
        PlatformDataMigrationDomainPreCheckSummary {
            errors: None,
            total_domains: None,
            valid_domains: None,
        }
    }
}

