/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PlatformDataIntegrationFederationOidcSummary : Platform Data Integration Federation OIDC Summary
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformDataIntegrationFederationOidcSummary {
    /// ClientId
    #[serde(rename = "clientId", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// EndpointUrl
    #[serde(rename = "endpointUrl", skip_serializing_if = "Option::is_none")]
    pub endpoint_url: Option<String>,
}

impl PlatformDataIntegrationFederationOidcSummary {
    /// Platform Data Integration Federation OIDC Summary
    pub fn new() -> PlatformDataIntegrationFederationOidcSummary {
        PlatformDataIntegrationFederationOidcSummary {
            client_id: None,
            endpoint_url: None,
        }
    }
}

