/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PlatformDataMigrationRoleSummary : Platform Data Migration Role Summary
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformDataMigrationRoleSummary {
    /// Last Migrated
    #[serde(rename = "lastMigrated", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_migrated: Option<Option<String>>,
    #[serde(rename = "migrationState", skip_serializing_if = "Option::is_none")]
    pub migration_state: Option<models::PlatformDataMigrationState>,
    /// Role Name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Number of Users/Groups Assigned to Role
    #[serde(rename = "numberOfAssigments", skip_serializing_if = "Option::is_none")]
    pub number_of_assigments: Option<i32>,
    /// Number of Permissions Assigned to Role
    #[serde(rename = "numberOfPermissions", skip_serializing_if = "Option::is_none")]
    pub number_of_permissions: Option<i32>,
    /// Role Id
    #[serde(rename = "roleId", skip_serializing_if = "Option::is_none")]
    pub role_id: Option<i32>,
}

impl PlatformDataMigrationRoleSummary {
    /// Platform Data Migration Role Summary
    pub fn new() -> PlatformDataMigrationRoleSummary {
        PlatformDataMigrationRoleSummary {
            last_migrated: None,
            migration_state: None,
            name: None,
            number_of_assigments: None,
            number_of_permissions: None,
            role_id: None,
        }
    }
}

