/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProcessingLocationType : Processing Location of Site
/// Processing Location of Site
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProcessingLocationType {
    #[serde(rename = "UseWebSite")]
    UseWebSite,
    #[serde(rename = "UseDistributedEngine")]
    UseDistributedEngine,

}

impl std::fmt::Display for ProcessingLocationType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::UseWebSite => write!(f, "UseWebSite"),
            Self::UseDistributedEngine => write!(f, "UseDistributedEngine"),
        }
    }
}

impl Default for ProcessingLocationType {
    fn default() -> ProcessingLocationType {
        Self::UseWebSite
    }
}

