/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProxySiteViewModel : Sites
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProxySiteViewModel {
    /// EnableRdpProxy
    #[serde(rename = "enableRdpProxy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub enable_rdp_proxy: Option<Option<bool>>,
    /// EnableSshProxy
    #[serde(rename = "enableSshProxy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub enable_ssh_proxy: Option<Option<bool>>,
    /// RdpProxyPort
    #[serde(rename = "rdpProxyPort", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rdp_proxy_port: Option<Option<i32>>,
    /// RdpProxyPortInherited
    #[serde(rename = "rdpProxyPortInherited", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rdp_proxy_port_inherited: Option<Option<bool>>,
    /// SiteId
    #[serde(rename = "siteId", skip_serializing_if = "Option::is_none")]
    pub site_id: Option<i32>,
    /// SiteName
    #[serde(rename = "siteName", skip_serializing_if = "Option::is_none")]
    pub site_name: Option<String>,
    /// SshJumpboxAvailablePortRange
    #[serde(rename = "sshJumpboxAvailablePortRange", skip_serializing_if = "Option::is_none")]
    pub ssh_jumpbox_available_port_range: Option<String>,
    /// SshProxyPort
    #[serde(rename = "sshProxyPort", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ssh_proxy_port: Option<Option<i32>>,
    /// SshProxyPortInherited
    #[serde(rename = "sshProxyPortInherited", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ssh_proxy_port_inherited: Option<Option<bool>>,
}

impl ProxySiteViewModel {
    /// Sites
    pub fn new() -> ProxySiteViewModel {
        ProxySiteViewModel {
            enable_rdp_proxy: None,
            enable_ssh_proxy: None,
            rdp_proxy_port: None,
            rdp_proxy_port_inherited: None,
            site_id: None,
            site_name: None,
            ssh_jumpbox_available_port_range: None,
            ssh_proxy_port: None,
            ssh_proxy_port_inherited: None,
        }
    }
}

