/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RdpProxyConfigurationViewModel : RdpProxyConfigurationViewModel
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RdpProxyConfigurationViewModel {
    /// Allows users to select a site when launching or generating proxy credentials for a RDP proxied secret
    #[serde(rename = "allowSiteSelectionForActiveDirectoryAccounts", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub allow_site_selection_for_active_directory_accounts: Option<Option<bool>>,
    /// The number of days to store RDP proxy logs before they are rolled over
    #[serde(rename = "daysToKeepOperationalLogs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub days_to_keep_operational_logs: Option<Option<i32>>,
    /// Whether or not to enable the RDP proxy
    #[serde(rename = "enableRdpProxy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub enable_rdp_proxy: Option<Option<bool>>,
    /// Whether or not to enforce certificate validation on remote hosts that the proxy connects to
    #[serde(rename = "enableRemoteHostValidation", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub enable_remote_host_validation: Option<Option<bool>>,
    /// IsCloud
    #[serde(rename = "isCloud", skip_serializing_if = "Option::is_none")]
    pub is_cloud: Option<bool>,
    /// Whether or not new RDP-enabled secrets should be created with 'Proxy Enabled' set
    #[serde(rename = "proxyNewSecretsByDefault", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub proxy_new_secrets_by_default: Option<Option<bool>>,
    /// The port that the RDP proxy will run on
    #[serde(rename = "rdpProxyPort", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rdp_proxy_port: Option<Option<i32>>,
    #[serde(rename = "rdpServerCertificate", skip_serializing_if = "Option::is_none")]
    pub rdp_server_certificate: Option<Box<models::RdpProxyCertificateViewModel>>,
    /// The certificate that is server when connections begin to the RDP proxy (used \"Content-Type: multipart/form-data\" only)
    #[serde(rename = "rdpServerCertificateMultipart", skip_serializing_if = "Option::is_none")]
    pub rdp_server_certificate_multipart: Option<std::path::PathBuf>,
    /// The password used to protect the certificate (only used for updating with \"Content-Type: multipart/form-data\" only)
    #[serde(rename = "rdpServerCertificateMultipartPassword", skip_serializing_if = "Option::is_none")]
    pub rdp_server_certificate_multipart_password: Option<String>,
}

impl RdpProxyConfigurationViewModel {
    /// RdpProxyConfigurationViewModel
    pub fn new() -> RdpProxyConfigurationViewModel {
        RdpProxyConfigurationViewModel {
            allow_site_selection_for_active_directory_accounts: None,
            days_to_keep_operational_logs: None,
            enable_rdp_proxy: None,
            enable_remote_host_validation: None,
            is_cloud: None,
            proxy_new_secrets_by_default: None,
            rdp_proxy_port: None,
            rdp_server_certificate: None,
            rdp_server_certificate_multipart: None,
            rdp_server_certificate_multipart_password: None,
        }
    }
}

