/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RecurringScheduleValueType : The type of schedule constraint
/// The type of schedule constraint
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RecurringScheduleValueType {
    #[serde(rename = "SpecificTime")]
    SpecificTime,
    #[serde(rename = "DayOfWeek")]
    DayOfWeek,
    #[serde(rename = "DayOfMonth")]
    DayOfMonth,
    #[serde(rename = "WeekOfMonth")]
    WeekOfMonth,
    #[serde(rename = "WeekOfMonthDay")]
    WeekOfMonthDay,

}

impl std::fmt::Display for RecurringScheduleValueType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SpecificTime => write!(f, "SpecificTime"),
            Self::DayOfWeek => write!(f, "DayOfWeek"),
            Self::DayOfMonth => write!(f, "DayOfMonth"),
            Self::WeekOfMonth => write!(f, "WeekOfMonth"),
            Self::WeekOfMonthDay => write!(f, "WeekOfMonthDay"),
        }
    }
}

impl Default for RecurringScheduleValueType {
    fn default() -> RecurringScheduleValueType {
        Self::SpecificTime
    }
}

