/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReportScheduleSummaryModel : Report Schedule Summary
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReportScheduleSummaryModel {
    #[serde(rename = "changeType", skip_serializing_if = "Option::is_none")]
    pub change_type: Option<models::ScheduleChangeType>,
    /// Deleted
    #[serde(rename = "deleted", skip_serializing_if = "Option::is_none")]
    pub deleted: Option<bool>,
    /// Description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// DateTime of Last Run
    #[serde(rename = "lastRun", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_run: Option<Option<String>>,
    /// HistoryId of Last Run
    #[serde(rename = "lastRunHistoryId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_run_history_id: Option<Option<i32>>,
    /// Name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Report Id
    #[serde(rename = "reportId", skip_serializing_if = "Option::is_none")]
    pub report_id: Option<i32>,
    /// Report Name
    #[serde(rename = "reportName", skip_serializing_if = "Option::is_none")]
    pub report_name: Option<String>,
    /// Schedule Report Id
    #[serde(rename = "scheduleReportId", skip_serializing_if = "Option::is_none")]
    pub schedule_report_id: Option<i32>,
    /// Send Report via Email
    #[serde(rename = "sendEmail", skip_serializing_if = "Option::is_none")]
    pub send_email: Option<bool>,
    /// Number of reports stored for this schedule
    #[serde(rename = "storedReportCount", skip_serializing_if = "Option::is_none")]
    pub stored_report_count: Option<i32>,
}

impl ReportScheduleSummaryModel {
    /// Report Schedule Summary
    pub fn new() -> ReportScheduleSummaryModel {
        ReportScheduleSummaryModel {
            change_type: None,
            deleted: None,
            description: None,
            last_run: None,
            last_run_history_id: None,
            name: None,
            report_id: None,
            report_name: None,
            schedule_report_id: None,
            send_email: None,
            stored_report_count: None,
        }
    }
}

