/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReportCategoryCreateModel : Report Category Create Model
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReportCategoryCreateModel {
    /// Report Category Description
    #[serde(rename = "reportCategoryDescription", skip_serializing_if = "Option::is_none")]
    pub report_category_description: Option<String>,
    /// Report Category Name
    #[serde(rename = "reportCategoryName", skip_serializing_if = "Option::is_none")]
    pub report_category_name: Option<String>,
    /// Report Category Sort Order, when null will be added at the end
    #[serde(rename = "sortOrder", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sort_order: Option<Option<i32>>,
}

impl ReportCategoryCreateModel {
    /// Report Category Create Model
    pub fn new() -> ReportCategoryCreateModel {
        ReportCategoryCreateModel {
            report_category_description: None,
            report_category_name: None,
            sort_order: None,
        }
    }
}

