/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RoleModel : Role
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoleModel {
    /// Created
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    /// Enabled
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Role Id
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Is System Role
    #[serde(rename = "isSystem", skip_serializing_if = "Option::is_none")]
    pub is_system: Option<bool>,
    /// Name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl RoleModel {
    /// Role
    pub fn new() -> RoleModel {
        RoleModel {
            created: None,
            enabled: None,
            id: None,
            is_system: None,
            name: None,
        }
    }
}

