/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SafeFileHandle : SafeFileHandle
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SafeFileHandle {
    /// IsClosed
    #[serde(rename = "isClosed", skip_serializing_if = "Option::is_none")]
    pub is_closed: Option<bool>,
    /// IsInvalid
    #[serde(rename = "isInvalid", skip_serializing_if = "Option::is_none")]
    pub is_invalid: Option<bool>,
}

impl SafeFileHandle {
    /// SafeFileHandle
    pub fn new() -> SafeFileHandle {
        SafeFileHandle {
            is_closed: None,
            is_invalid: None,
        }
    }
}

