/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScannerBundle : Scanners
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScannerBundle {
    /// DefaultDiscoverySettingForDisplays
    #[serde(rename = "defaultDiscoverySettingForDisplays", skip_serializing_if = "Option::is_none")]
    pub default_discovery_setting_for_displays: Option<Vec<models::DefaultDiscoverySettingForDisplay>>,
    #[serde(rename = "discoveryScannerDetail", skip_serializing_if = "Option::is_none")]
    pub discovery_scanner_detail: Option<Box<models::DiscoveryScannerDetailModel>>,
    #[serde(rename = "scanner", skip_serializing_if = "Option::is_none")]
    pub scanner: Option<Box<models::DiscoveryScannerModel>>,
}

impl ScannerBundle {
    /// Scanners
    pub fn new() -> ScannerBundle {
        ScannerBundle {
            default_discovery_setting_for_displays: None,
            discovery_scanner_detail: None,
            scanner: None,
        }
    }
}

