/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScriptSqlParamType : ParameterDbType
/// ParameterDbType
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ScriptSqlParamType {
    #[serde(rename = "AnsiString")]
    AnsiString,
    #[serde(rename = "Binary")]
    Binary,
    #[serde(rename = "Byte")]
    Byte,
    #[serde(rename = "Boolean")]
    Boolean,
    #[serde(rename = "Currency")]
    Currency,
    #[serde(rename = "Date")]
    Date,
    #[serde(rename = "DateTime")]
    DateTime,
    #[serde(rename = "Decimal")]
    Decimal,
    #[serde(rename = "Double")]
    Double,
    #[serde(rename = "Guid")]
    Guid,
    #[serde(rename = "Int16")]
    Int16,
    #[serde(rename = "Int32")]
    Int32,
    #[serde(rename = "Int64")]
    Int64,
    #[serde(rename = "Object")]
    Object,
    #[serde(rename = "SByte")]
    SByte,
    #[serde(rename = "Single")]
    Single,
    #[serde(rename = "String")]
    String,
    #[serde(rename = "Time")]
    Time,
    #[serde(rename = "UInt16")]
    UInt16,
    #[serde(rename = "UInt32")]
    UInt32,
    #[serde(rename = "UInt64")]
    UInt64,
    #[serde(rename = "VarNumeric")]
    VarNumeric,
    #[serde(rename = "AnsiStringFixedLength")]
    AnsiStringFixedLength,
    #[serde(rename = "StringFixedLength")]
    StringFixedLength,
    #[serde(rename = "Xml")]
    Xml,
    #[serde(rename = "DateTime2")]
    DateTime2,
    #[serde(rename = "DateTimeOffset")]
    DateTimeOffset,

}

impl std::fmt::Display for ScriptSqlParamType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AnsiString => write!(f, "AnsiString"),
            Self::Binary => write!(f, "Binary"),
            Self::Byte => write!(f, "Byte"),
            Self::Boolean => write!(f, "Boolean"),
            Self::Currency => write!(f, "Currency"),
            Self::Date => write!(f, "Date"),
            Self::DateTime => write!(f, "DateTime"),
            Self::Decimal => write!(f, "Decimal"),
            Self::Double => write!(f, "Double"),
            Self::Guid => write!(f, "Guid"),
            Self::Int16 => write!(f, "Int16"),
            Self::Int32 => write!(f, "Int32"),
            Self::Int64 => write!(f, "Int64"),
            Self::Object => write!(f, "Object"),
            Self::SByte => write!(f, "SByte"),
            Self::Single => write!(f, "Single"),
            Self::String => write!(f, "String"),
            Self::Time => write!(f, "Time"),
            Self::UInt16 => write!(f, "UInt16"),
            Self::UInt32 => write!(f, "UInt32"),
            Self::UInt64 => write!(f, "UInt64"),
            Self::VarNumeric => write!(f, "VarNumeric"),
            Self::AnsiStringFixedLength => write!(f, "AnsiStringFixedLength"),
            Self::StringFixedLength => write!(f, "StringFixedLength"),
            Self::Xml => write!(f, "Xml"),
            Self::DateTime2 => write!(f, "DateTime2"),
            Self::DateTimeOffset => write!(f, "DateTimeOffset"),
        }
    }
}

impl Default for ScriptSqlParamType {
    fn default() -> ScriptSqlParamType {
        Self::AnsiString
    }
}

