/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretPolicyAuditSummary : Records
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretPolicyAuditSummary {
    /// Action
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
    /// DatabaseName
    #[serde(rename = "databaseName", skip_serializing_if = "Option::is_none")]
    pub database_name: Option<String>,
    /// DateRecorded
    #[serde(rename = "dateRecorded", skip_serializing_if = "Option::is_none")]
    pub date_recorded: Option<String>,
    /// MachineName
    #[serde(rename = "machineName", skip_serializing_if = "Option::is_none")]
    pub machine_name: Option<String>,
    /// Notes
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    /// SecretPolicyAuditId
    #[serde(rename = "secretPolicyAuditId", skip_serializing_if = "Option::is_none")]
    pub secret_policy_audit_id: Option<i32>,
    /// UserId
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    /// Username
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

impl SecretPolicyAuditSummary {
    /// Records
    pub fn new() -> SecretPolicyAuditSummary {
        SecretPolicyAuditSummary {
            action: None,
            database_name: None,
            date_recorded: None,
            machine_name: None,
            notes: None,
            secret_policy_audit_id: None,
            user_id: None,
            username: None,
        }
    }
}

