/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretImportXmlProcessDataModel : Data
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretImportXmlProcessDataModel {
    /// ChangeRemotePasswords
    #[serde(rename = "changeRemotePasswords", skip_serializing_if = "Option::is_none")]
    pub change_remote_passwords: Option<bool>,
    /// ImportWithFolder
    #[serde(rename = "importWithFolder", skip_serializing_if = "Option::is_none")]
    pub import_with_folder: Option<bool>,
    /// InheritFolderPermissions
    #[serde(rename = "inheritFolderPermissions", skip_serializing_if = "Option::is_none")]
    pub inherit_folder_permissions: Option<bool>,
    /// Xml
    #[serde(rename = "xml", skip_serializing_if = "Option::is_none")]
    pub xml: Option<String>,
}

impl SecretImportXmlProcessDataModel {
    /// Data
    pub fn new() -> SecretImportXmlProcessDataModel {
        SecretImportXmlProcessDataModel {
            change_remote_passwords: None,
            import_with_folder: None,
            inherit_folder_permissions: None,
            xml: None,
        }
    }
}

