/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretPermissionEnum : Secret Permissions
/// Secret Permissions
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SecretPermissionEnum {
    #[serde(rename = "InheritPermission")]
    InheritPermission,
    #[serde(rename = "CopyPermission")]
    CopyPermission,

}

impl std::fmt::Display for SecretPermissionEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::InheritPermission => write!(f, "InheritPermission"),
            Self::CopyPermission => write!(f, "CopyPermission"),
        }
    }
}

impl Default for SecretPermissionEnum {
    fn default() -> SecretPermissionEnum {
        Self::InheritPermission
    }
}

