/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretSessionSummaryModel : SecretSessionSummaryModel
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretSessionSummaryModel {
    /// Active
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    /// EndDate
    #[serde(rename = "endDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<Option<String>>,
    /// LauncherTypeId
    #[serde(rename = "launcherTypeId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub launcher_type_id: Option<Option<i32>>,
    /// MachineName
    #[serde(rename = "machineName", skip_serializing_if = "Option::is_none")]
    pub machine_name: Option<String>,
    /// SecretId
    #[serde(rename = "secretId", skip_serializing_if = "Option::is_none")]
    pub secret_id: Option<i32>,
    /// SecretName
    #[serde(rename = "secretName", skip_serializing_if = "Option::is_none")]
    pub secret_name: Option<String>,
    /// SecretSessionId
    #[serde(rename = "secretSessionId", skip_serializing_if = "Option::is_none")]
    pub secret_session_id: Option<i32>,
    /// StartDate
    #[serde(rename = "startDate", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
    /// UserId
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    /// UserName
    #[serde(rename = "userName", skip_serializing_if = "Option::is_none")]
    pub user_name: Option<String>,
}

impl SecretSessionSummaryModel {
    /// SecretSessionSummaryModel
    pub fn new() -> SecretSessionSummaryModel {
        SecretSessionSummaryModel {
            active: None,
            end_date: None,
            launcher_type_id: None,
            machine_name: None,
            secret_id: None,
            secret_name: None,
            secret_session_id: None,
            start_date: None,
            user_id: None,
            user_name: None,
        }
    }
}

