/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretPlatformPermissionsRequest : Represents a request to check or assign ACL role for a user on a specified secret.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretPlatformPermissionsRequest {
    /// ACL Role name of role to check or assign to secret.
    #[serde(rename = "aclRoleName", skip_serializing_if = "Option::is_none")]
    pub acl_role_name: Option<String>,
    /// Secret Id to check or assign role for a user.
    #[serde(rename = "secretId", skip_serializing_if = "Option::is_none")]
    pub secret_id: Option<i32>,
    /// Username of user to check or assign role on secret.
    #[serde(rename = "userName", skip_serializing_if = "Option::is_none")]
    pub user_name: Option<String>,
}

impl SecretPlatformPermissionsRequest {
    /// Represents a request to check or assign ACL role for a user on a specified secret.
    pub fn new() -> SecretPlatformPermissionsRequest {
        SecretPlatformPermissionsRequest {
            acl_role_name: None,
            secret_id: None,
            user_name: None,
        }
    }
}

