/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretViewedByUserModel : Query results
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretViewedByUserModel {
    /// CanView
    #[serde(rename = "canView", skip_serializing_if = "Option::is_none")]
    pub can_view: Option<bool>,
    /// DisplayName
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// DisplayNameAndUserName
    #[serde(rename = "displayNameAndUserName", skip_serializing_if = "Option::is_none")]
    pub display_name_and_user_name: Option<String>,
    /// Domain
    #[serde(rename = "domain", skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    /// Enabled
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// UserId
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    /// UserName
    #[serde(rename = "userName", skip_serializing_if = "Option::is_none")]
    pub user_name: Option<String>,
}

impl SecretViewedByUserModel {
    /// Query results
    pub fn new() -> SecretViewedByUserModel {
        SecretViewedByUserModel {
            can_view: None,
            display_name: None,
            display_name_and_user_name: None,
            domain: None,
            enabled: None,
            user_id: None,
            user_name: None,
        }
    }
}

