/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretLauncherSessionArgs : Secret Launcher Session Args
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretLauncherSessionArgs {
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<models::SessionActions>,
    /// Message To Send
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// Secret Associated To Session
    #[serde(rename = "secretId", skip_serializing_if = "Option::is_none")]
    pub secret_id: Option<i32>,
    /// Secret Session Id, either the ID, Session Key, or Session GUID must be supplied
    #[serde(rename = "secretSessionId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub secret_session_id: Option<Option<i32>>,
    /// Secret Session Key, either the ID, Session Key, or Session GUID must be supplied
    #[serde(rename = "secretSessionKey", skip_serializing_if = "Option::is_none")]
    pub secret_session_key: Option<String>,
    /// Secret Session Guid, this can be either the secret sessino key or launcher GUID, the ID, Session Key, or Session GUID must be supplied
    #[serde(rename = "sessionGuid", skip_serializing_if = "Option::is_none")]
    pub session_guid: Option<String>,
}

impl SecretLauncherSessionArgs {
    /// Secret Launcher Session Args
    pub fn new() -> SecretLauncherSessionArgs {
        SecretLauncherSessionArgs {
            action: None,
            message: None,
            secret_id: None,
            secret_session_id: None,
            secret_session_key: None,
            session_guid: None,
        }
    }
}

