/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretPolicyUpdateModelV2 : Secret Policy Update Model V2
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretPolicyUpdateModelV2 {
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<Box<models::UpdateFieldValueOfBoolean>>,
    #[serde(rename = "generalItems", skip_serializing_if = "Option::is_none")]
    pub general_items: Option<Box<models::SecretPolicyGeneralItemsUpdateModel>>,
    #[serde(rename = "launcherItems", skip_serializing_if = "Option::is_none")]
    pub launcher_items: Option<Box<models::SecretPolicyLauncherItemsUpdateModel>>,
    #[serde(rename = "rpcItems", skip_serializing_if = "Option::is_none")]
    pub rpc_items: Option<Box<models::SecretPolicyRpcItemsUpdateModel>>,
    #[serde(rename = "secretPolicyDescription", skip_serializing_if = "Option::is_none")]
    pub secret_policy_description: Option<Box<models::UpdateFieldValueOfString>>,
    #[serde(rename = "secretPolicyName", skip_serializing_if = "Option::is_none")]
    pub secret_policy_name: Option<Box<models::UpdateFieldValueOfString>>,
    #[serde(rename = "securityItems", skip_serializing_if = "Option::is_none")]
    pub security_items: Option<Box<models::SecretPolicySecurityItemsUpdateModel>>,
}

impl SecretPolicyUpdateModelV2 {
    /// Secret Policy Update Model V2
    pub fn new() -> SecretPolicyUpdateModelV2 {
        SecretPolicyUpdateModelV2 {
            active: None,
            general_items: None,
            launcher_items: None,
            rpc_items: None,
            secret_policy_description: None,
            secret_policy_name: None,
            security_items: None,
        }
    }
}

