/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretServerSettingsQuery : Filter
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretServerSettingsQuery {
    /// LoadAdvancedSettings
    #[serde(rename = "loadAdvancedSettings", skip_serializing_if = "Option::is_none")]
    pub load_advanced_settings: Option<bool>,
    /// LoadAll
    #[serde(rename = "loadAll", skip_serializing_if = "Option::is_none")]
    pub load_all: Option<bool>,
    /// LoadApplicationSettings
    #[serde(rename = "loadApplicationSettings", skip_serializing_if = "Option::is_none")]
    pub load_application_settings: Option<bool>,
    /// LoadEmail
    #[serde(rename = "loadEmail", skip_serializing_if = "Option::is_none")]
    pub load_email: Option<bool>,
    /// LoadFolderSettings
    #[serde(rename = "loadFolderSettings", skip_serializing_if = "Option::is_none")]
    pub load_folder_settings: Option<bool>,
    /// LoadLauncherSettings
    #[serde(rename = "loadLauncherSettings", skip_serializing_if = "Option::is_none")]
    pub load_launcher_settings: Option<bool>,
    /// LoadLicenses
    #[serde(rename = "loadLicenses", skip_serializing_if = "Option::is_none")]
    pub load_licenses: Option<bool>,
    /// LoadLocalUserPasswords
    #[serde(rename = "loadLocalUserPasswords", skip_serializing_if = "Option::is_none")]
    pub load_local_user_passwords: Option<bool>,
    /// LoadLogin
    #[serde(rename = "loadLogin", skip_serializing_if = "Option::is_none")]
    pub load_login: Option<bool>,
    /// LoadPermissionOptions
    #[serde(rename = "loadPermissionOptions", skip_serializing_if = "Option::is_none")]
    pub load_permission_options: Option<bool>,
    /// LoadProtocolHandlerSettings
    #[serde(rename = "loadProtocolHandlerSettings", skip_serializing_if = "Option::is_none")]
    pub load_protocol_handler_settings: Option<bool>,
    /// LoadSaml
    #[serde(rename = "loadSaml", skip_serializing_if = "Option::is_none")]
    pub load_saml: Option<bool>,
    /// LoadSecurity
    #[serde(rename = "loadSecurity", skip_serializing_if = "Option::is_none")]
    pub load_security: Option<bool>,
    /// LoadSessionRecording
    #[serde(rename = "loadSessionRecording", skip_serializing_if = "Option::is_none")]
    pub load_session_recording: Option<bool>,
    /// LoadSshCommands
    #[serde(rename = "loadSshCommands", skip_serializing_if = "Option::is_none")]
    pub load_ssh_commands: Option<bool>,
    /// LoadTicketSystem
    #[serde(rename = "loadTicketSystem", skip_serializing_if = "Option::is_none")]
    pub load_ticket_system: Option<bool>,
    /// LoadUserExperience
    #[serde(rename = "loadUserExperience", skip_serializing_if = "Option::is_none")]
    pub load_user_experience: Option<bool>,
    /// LoadUserInterface
    #[serde(rename = "loadUserInterface", skip_serializing_if = "Option::is_none")]
    pub load_user_interface: Option<bool>,
}

impl SecretServerSettingsQuery {
    /// Filter
    pub fn new() -> SecretServerSettingsQuery {
        SecretServerSettingsQuery {
            load_advanced_settings: None,
            load_all: None,
            load_application_settings: None,
            load_email: None,
            load_folder_settings: None,
            load_launcher_settings: None,
            load_licenses: None,
            load_local_user_passwords: None,
            load_login: None,
            load_permission_options: None,
            load_protocol_handler_settings: None,
            load_saml: None,
            load_security: None,
            load_session_recording: None,
            load_ssh_commands: None,
            load_ticket_system: None,
            load_user_experience: None,
            load_user_interface: None,
        }
    }
}

