/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretPolicyCreateModelV2 : Secret Policy Create Model V2
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretPolicyCreateModelV2 {
    /// Indicates the policy is active
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(rename = "generalItems", skip_serializing_if = "Option::is_none")]
    pub general_items: Option<Box<models::SecretPolicyGeneralItemsCreateModel>>,
    #[serde(rename = "launcherItems", skip_serializing_if = "Option::is_none")]
    pub launcher_items: Option<Box<models::SecretPolicyLauncherItemsCreateModel>>,
    #[serde(rename = "rpcItems", skip_serializing_if = "Option::is_none")]
    pub rpc_items: Option<Box<models::SecretPolicyRpcItemsCreateModel>>,
    /// Secret Policy Description
    #[serde(rename = "secretPolicyDescription", skip_serializing_if = "Option::is_none")]
    pub secret_policy_description: Option<String>,
    /// Secret Policy Name
    #[serde(rename = "secretPolicyName", skip_serializing_if = "Option::is_none")]
    pub secret_policy_name: Option<String>,
    #[serde(rename = "securityItems", skip_serializing_if = "Option::is_none")]
    pub security_items: Option<Box<models::SecretPolicySecurityItemsCreateModel>>,
}

impl SecretPolicyCreateModelV2 {
    /// Secret Policy Create Model V2
    pub fn new() -> SecretPolicyCreateModelV2 {
        SecretPolicyCreateModelV2 {
            active: None,
            general_items: None,
            launcher_items: None,
            rpc_items: None,
            secret_policy_description: None,
            secret_policy_name: None,
            security_items: None,
        }
    }
}

