/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretDependencyRunScript : The RunScript details of a Dependency that directly runs a Script
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretDependencyRunScript {
    /// The machine name that the Secret Dependency runs on
    #[serde(rename = "machineName", skip_serializing_if = "Option::is_none")]
    pub machine_name: Option<String>,
    /// Connection arguments used for ODBC connections
    #[serde(rename = "odbcConnectionArguments", skip_serializing_if = "Option::is_none")]
    pub odbc_connection_arguments: Option<Vec<models::SecretDependencyOdbcConnectionArg>>,
    /// Parameter script arguments used by the script
    #[serde(rename = "scriptArguments", skip_serializing_if = "Option::is_none")]
    pub script_arguments: Option<Vec<models::SecretDependencyUniversalScriptArgument>>,
    /// The Id of the script that the Secret Dependency runs. (If directly running a script)
    #[serde(rename = "scriptId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub script_id: Option<Option<i32>>,
    /// The Name of the script that the Secret Dependency runs.
    #[serde(rename = "scriptName", skip_serializing_if = "Option::is_none")]
    pub script_name: Option<String>,
    /// The service name of the Secret Dependency
    #[serde(rename = "serviceName", skip_serializing_if = "Option::is_none")]
    pub service_name: Option<String>,
}

impl SecretDependencyRunScript {
    /// The RunScript details of a Dependency that directly runs a Script
    pub fn new() -> SecretDependencyRunScript {
        SecretDependencyRunScript {
            machine_name: None,
            odbc_connection_arguments: None,
            script_arguments: None,
            script_id: None,
            script_name: None,
            service_name: None,
        }
    }
}

