/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretPolicyItemOfOptionalInt32 : Site Id
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretPolicyItemOfOptionalInt32 {
    /// ParentPolicyItemId
    #[serde(rename = "parentPolicyItemId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent_policy_item_id: Option<Option<i32>>,
    #[serde(rename = "policyApplyType", skip_serializing_if = "Option::is_none")]
    pub policy_apply_type: Option<models::PolicyApplyType>,
    /// PolicyItemId
    #[serde(rename = "policyItemId", skip_serializing_if = "Option::is_none")]
    pub policy_item_id: Option<i32>,
    /// Value
    #[serde(rename = "value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub value: Option<Option<i32>>,
}

impl SecretPolicyItemOfOptionalInt32 {
    /// Site Id
    pub fn new() -> SecretPolicyItemOfOptionalInt32 {
        SecretPolicyItemOfOptionalInt32 {
            parent_policy_item_id: None,
            policy_apply_type: None,
            policy_item_id: None,
            value: None,
        }
    }
}

