/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretDetailGeneralViewModel : Secret Detail General View Model
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretDetailGeneralViewModel {
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<Box<models::ViewFieldValueOfBoolean>>,
    #[serde(rename = "autoChangePassword", skip_serializing_if = "Option::is_none")]
    pub auto_change_password: Option<Box<models::ViewFieldValueOfBoolean>>,
    /// CanGenerateSshKey
    #[serde(rename = "canGenerateSshKey", skip_serializing_if = "Option::is_none")]
    pub can_generate_ssh_key: Option<bool>,
    #[serde(rename = "enableInheritSecretPolicy", skip_serializing_if = "Option::is_none")]
    pub enable_inherit_secret_policy: Option<Box<models::ViewFieldValueOfBoolean>>,
    #[serde(rename = "expiration", skip_serializing_if = "Option::is_none")]
    pub expiration: Option<Box<models::ViewFieldValueOfString>>,
    /// Fields
    #[serde(rename = "fields", skip_serializing_if = "Option::is_none")]
    pub fields: Option<Vec<models::ViewTemplateFieldOfString>>,
    #[serde(rename = "folder", skip_serializing_if = "Option::is_none")]
    pub folder: Option<Box<models::ViewFieldValueOfOptionalInt32>>,
    #[serde(rename = "heartbeatEnabled", skip_serializing_if = "Option::is_none")]
    pub heartbeat_enabled: Option<Box<models::ViewFieldValueOfBoolean>>,
    /// Id
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// IsFavorite
    #[serde(rename = "isFavorite", skip_serializing_if = "Option::is_none")]
    pub is_favorite: Option<bool>,
    #[serde(rename = "isOutOfSync", skip_serializing_if = "Option::is_none")]
    pub is_out_of_sync: Option<Box<models::ViewFieldValueOfBoolean>>,
    /// IsTotpEnabled
    #[serde(rename = "isTotpEnabled", skip_serializing_if = "Option::is_none")]
    pub is_totp_enabled: Option<bool>,
    #[serde(rename = "lastHeartBeatCheck", skip_serializing_if = "Option::is_none")]
    pub last_heart_beat_check: Option<Box<models::ViewFieldValueOfOptionalDateTime>>,
    #[serde(rename = "lastHeartBeatStatus", skip_serializing_if = "Option::is_none")]
    pub last_heart_beat_status: Option<Box<models::ViewFieldValueOfSecretDetailHeartbeatStatus>>,
    /// Launchers
    #[serde(rename = "launchers", skip_serializing_if = "Option::is_none")]
    pub launchers: Option<Vec<models::SecretDetailLauncher>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<Box<models::ViewFieldValueOfString>>,
    #[serde(rename = "outOfSyncReason", skip_serializing_if = "Option::is_none")]
    pub out_of_sync_reason: Option<Box<models::ViewFieldValueOfString>>,
    #[serde(rename = "passwordCompliance", skip_serializing_if = "Option::is_none")]
    pub password_compliance: Option<models::SecretPasswordComplianceCode>,
    #[serde(rename = "secretPolicy", skip_serializing_if = "Option::is_none")]
    pub secret_policy: Option<Box<models::ViewFieldValueOfOptionalInt32>>,
    #[serde(rename = "site", skip_serializing_if = "Option::is_none")]
    pub site: Option<Box<models::ViewFieldValueOfOptionalInt32>>,
    /// SlugPrivateKey
    #[serde(rename = "slugPrivateKey", skip_serializing_if = "Option::is_none")]
    pub slug_private_key: Option<String>,
    /// SlugPublicKey
    #[serde(rename = "slugPublicKey", skip_serializing_if = "Option::is_none")]
    pub slug_public_key: Option<String>,
    #[serde(rename = "template", skip_serializing_if = "Option::is_none")]
    pub template: Option<Box<models::ViewFieldValueOfOptionalInt32>>,
    /// TotpPasswordSlug
    #[serde(rename = "totpPasswordSlug", skip_serializing_if = "Option::is_none")]
    pub totp_password_slug: Option<String>,
}

impl SecretDetailGeneralViewModel {
    /// Secret Detail General View Model
    pub fn new() -> SecretDetailGeneralViewModel {
        SecretDetailGeneralViewModel {
            active: None,
            auto_change_password: None,
            can_generate_ssh_key: None,
            enable_inherit_secret_policy: None,
            expiration: None,
            fields: None,
            folder: None,
            heartbeat_enabled: None,
            id: None,
            is_favorite: None,
            is_out_of_sync: None,
            is_totp_enabled: None,
            last_heart_beat_check: None,
            last_heart_beat_status: None,
            launchers: None,
            name: None,
            out_of_sync_reason: None,
            password_compliance: None,
            secret_policy: None,
            site: None,
            slug_private_key: None,
            slug_public_key: None,
            template: None,
            totp_password_slug: None,
        }
    }
}

