/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretTemplateLauncherUpdateModel : Update mapping values between secret template and launcher
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretTemplateLauncherUpdateModel {
    #[serde(rename = "allowList", skip_serializing_if = "Option::is_none")]
    pub allow_list: Option<Box<models::UpdateFieldValueOfOptionalInt32>>,
    #[serde(rename = "connectAsCommand", skip_serializing_if = "Option::is_none")]
    pub connect_as_command: Option<Box<models::UpdateFieldValueOfString>>,
    #[serde(rename = "connectAsCommandResponse", skip_serializing_if = "Option::is_none")]
    pub connect_as_command_response: Option<Box<models::UpdateFieldValueOfString>>,
    #[serde(rename = "connectAsTimeoutInSeconds", skip_serializing_if = "Option::is_none")]
    pub connect_as_timeout_in_seconds: Option<Box<models::UpdateFieldValueOfOptionalInt32>>,
    #[serde(rename = "denyList", skip_serializing_if = "Option::is_none")]
    pub deny_list: Option<Box<models::UpdateFieldValueOfOptionalInt32>>,
    #[serde(rename = "expectedPromptEnding", skip_serializing_if = "Option::is_none")]
    pub expected_prompt_ending: Option<Box<models::UpdateFieldValueOfString>>,
    #[serde(rename = "fields", skip_serializing_if = "Option::is_none")]
    pub fields: Option<Box<models::UpdateFieldValueOfSecretTemplateLauncherFieldValueModelLeftSquareBracketRightSquareBracket>>,
    #[serde(rename = "includeMachinesFromDependencies", skip_serializing_if = "Option::is_none")]
    pub include_machines_from_dependencies: Option<Box<models::UpdateFieldValueOfBoolean>>,
    #[serde(rename = "lineEnding", skip_serializing_if = "Option::is_none")]
    pub line_ending: Option<Box<models::UpdateFieldValueOfOptionalLauncherConnectAsLineEnding>>,
    #[serde(rename = "restrictAs", skip_serializing_if = "Option::is_none")]
    pub restrict_as: Option<Box<models::UpdateFieldValueOfOptionalInt32>>,
    #[serde(rename = "restrictBySecretField", skip_serializing_if = "Option::is_none")]
    pub restrict_by_secret_field: Option<Box<models::UpdateFieldValueOfOptionalInt32>>,
    #[serde(rename = "restrictUserInput", skip_serializing_if = "Option::is_none")]
    pub restrict_user_input: Option<Box<models::UpdateFieldValueOfBoolean>>,
}

impl SecretTemplateLauncherUpdateModel {
    /// Update mapping values between secret template and launcher
    pub fn new() -> SecretTemplateLauncherUpdateModel {
        SecretTemplateLauncherUpdateModel {
            allow_list: None,
            connect_as_command: None,
            connect_as_command_response: None,
            connect_as_timeout_in_seconds: None,
            deny_list: None,
            expected_prompt_ending: None,
            fields: None,
            include_machines_from_dependencies: None,
            line_ending: None,
            restrict_as: None,
            restrict_by_secret_field: None,
            restrict_user_input: None,
        }
    }
}

