/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretTemplatePermissionModel : Secret template
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretTemplatePermissionModel {
    /// Secret template ID
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<i32>>,
    /// Secret template name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl SecretTemplatePermissionModel {
    /// Secret template
    pub fn new() -> SecretTemplatePermissionModel {
        SecretTemplatePermissionModel {
            id: None,
            name: None,
        }
    }
}

