/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretChangePasswordArgs : Secret password change options
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretChangePasswordArgs {
    /// If the secret requires a comment to view or requires approval to view, a reason for accessing the secret must be provided.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// If the secret is DoubleLocked, this is the DoubleLock password needed to access the secret.
    #[serde(rename = "doubleLockPassword", skip_serializing_if = "Option::is_none")]
    pub double_lock_password: Option<String>,
    /// Force the secret to be checked in, even if checked out by someone else. The user must have the \"Force Check In\" permission.
    #[serde(rename = "forceCheckIn", skip_serializing_if = "Option::is_none")]
    pub force_check_in: Option<bool>,
    /// If the secret is deactivated, this must be set to true in order to access the secret. The user must also have the \"View Inactive Secrets\" permission.
    #[serde(rename = "includeInactive", skip_serializing_if = "Option::is_none")]
    pub include_inactive: Option<bool>,
    /// New secret password.
    #[serde(rename = "newPassword", skip_serializing_if = "Option::is_none")]
    pub new_password: Option<String>,
    /// Don't check out the secret automatically.
    #[serde(rename = "noAutoCheckout", skip_serializing_if = "Option::is_none")]
    pub no_auto_checkout: Option<bool>,
    /// Prevent further RPC retries after max attempts reached
    #[serde(rename = "preventFurtherRetriesAfterMaxAttempts", skip_serializing_if = "Option::is_none")]
    pub prevent_further_retries_after_max_attempts: Option<bool>,
    #[serde(rename = "sshKeyArgs", skip_serializing_if = "Option::is_none")]
    pub ssh_key_args: Option<Box<models::RotateSshKeyArgs>>,
    /// If the secret requires a comment to view or requires approval and a user must provide a help desk a ticket number, this is the ticket number to the help desk request.
    #[serde(rename = "ticketNumber", skip_serializing_if = "Option::is_none")]
    pub ticket_number: Option<String>,
    /// If the secret requires a comment to view or requires approval and a user must provide a help desk a ticket number, this is the id of the help desk system configured in Secret Server that should be used to validate the ticket number.
    #[serde(rename = "ticketSystemId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ticket_system_id: Option<Option<i32>>,
}

impl SecretChangePasswordArgs {
    /// Secret password change options
    pub fn new() -> SecretChangePasswordArgs {
        SecretChangePasswordArgs {
            comment: None,
            double_lock_password: None,
            force_check_in: None,
            include_inactive: None,
            new_password: None,
            no_auto_checkout: None,
            prevent_further_retries_after_max_attempts: None,
            ssh_key_args: None,
            ticket_number: None,
            ticket_system_id: None,
        }
    }
}

