/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretAccessPendingRequestModel : The Secret Access Pending model object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretAccessPendingRequestModel {
    /// The Id of the Access Request Workflow Map.
    #[serde(rename = "accessRequestWorkflowMapId", skip_serializing_if = "Option::is_none")]
    pub access_request_workflow_map_id: Option<i32>,
    /// The Display Name of the Approver of the request
    #[serde(rename = "approverDisplayName", skip_serializing_if = "Option::is_none")]
    pub approver_display_name: Option<String>,
    /// Indicating if request has been completed
    #[serde(rename = "completed", skip_serializing_if = "Option::is_none")]
    pub completed: Option<bool>,
    /// The List of approving reviewers for the current approval step.
    #[serde(rename = "currentStepApprovers", skip_serializing_if = "Option::is_none")]
    pub current_step_approvers: Option<Vec<String>>,
    /// The List of reviewers for the current approval step.
    #[serde(rename = "currentStepReviewers", skip_serializing_if = "Option::is_none")]
    pub current_step_reviewers: Option<Vec<models::SecretAccessReviewer>>,
    /// Indicating if current user is restricted from viewing the request
    #[serde(rename = "currentUserRestrictedFromReviewing", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub current_user_restricted_from_reviewing: Option<Option<bool>>,
    /// The Expiration Date of the request
    #[serde(rename = "expirationDate", skip_serializing_if = "Option::is_none")]
    pub expiration_date: Option<String>,
    /// The Folder Id of the Secret associated to the access request.
    #[serde(rename = "folderId", skip_serializing_if = "Option::is_none")]
    pub folder_id: Option<i32>,
    /// Indicating if request is associated to a Work Flow
    #[serde(rename = "hasWorkflow", skip_serializing_if = "Option::is_none")]
    pub has_workflow: Option<bool>,
    /// The Comment of the request.
    #[serde(rename = "requestComment", skip_serializing_if = "Option::is_none")]
    pub request_comment: Option<String>,
    /// The Date of the request.
    #[serde(rename = "requestDate", skip_serializing_if = "Option::is_none")]
    pub request_date: Option<String>,
    /// The Id of the User requesting access.
    #[serde(rename = "requestingUserId", skip_serializing_if = "Option::is_none")]
    pub requesting_user_id: Option<i32>,
    /// The Username of the User requesting access.
    #[serde(rename = "requestUsername", skip_serializing_if = "Option::is_none")]
    pub request_username: Option<String>,
    /// The Comment of the response to the request
    #[serde(rename = "responseComment", skip_serializing_if = "Option::is_none")]
    pub response_comment: Option<String>,
    /// The Date of the response to the request
    #[serde(rename = "responseDate", skip_serializing_if = "Option::is_none")]
    pub response_date: Option<String>,
    /// The Review Status Message of the request
    #[serde(rename = "reviewStatusMessage", skip_serializing_if = "Option::is_none")]
    pub review_status_message: Option<String>,
    /// The Id of the Secret Access Request.
    #[serde(rename = "secretAccessRequestId", skip_serializing_if = "Option::is_none")]
    pub secret_access_request_id: Option<i32>,
    /// The Id of the Secret associated to the access request.
    #[serde(rename = "secretId", skip_serializing_if = "Option::is_none")]
    pub secret_id: Option<i32>,
    /// The Name of the Secret associated to the access request.
    #[serde(rename = "secretName", skip_serializing_if = "Option::is_none")]
    pub secret_name: Option<String>,
    /// The Start Date of the request.
    #[serde(rename = "startDate", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
    /// The Status of the request
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// The Status Description of the request
    #[serde(rename = "statusDescription", skip_serializing_if = "Option::is_none")]
    pub status_description: Option<String>,
    /// The Ticket Number of the request
    #[serde(rename = "ticketNumber", skip_serializing_if = "Option::is_none")]
    pub ticket_number: Option<String>,
    /// The Ticket System Id of the request
    #[serde(rename = "ticketSystemId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ticket_system_id: Option<Option<i32>>,
}

impl SecretAccessPendingRequestModel {
    /// The Secret Access Pending model object
    pub fn new() -> SecretAccessPendingRequestModel {
        SecretAccessPendingRequestModel {
            access_request_workflow_map_id: None,
            approver_display_name: None,
            completed: None,
            current_step_approvers: None,
            current_step_reviewers: None,
            current_user_restricted_from_reviewing: None,
            expiration_date: None,
            folder_id: None,
            has_workflow: None,
            request_comment: None,
            request_date: None,
            requesting_user_id: None,
            request_username: None,
            response_comment: None,
            response_date: None,
            review_status_message: None,
            secret_access_request_id: None,
            secret_id: None,
            secret_name: None,
            start_date: None,
            status: None,
            status_description: None,
            ticket_number: None,
            ticket_system_id: None,
        }
    }
}

