/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretAccessUpdateArgs : Secret Access Update paramaters
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretAccessUpdateArgs {
    #[serde(rename = "expirationDate", skip_serializing_if = "Option::is_none")]
    pub expiration_date: Option<Box<models::DateTimeOffset>>,
    /// Response Comment
    #[serde(rename = "responseComment", skip_serializing_if = "Option::is_none")]
    pub response_comment: Option<String>,
    /// Secret Access Request Id
    #[serde(rename = "secretAccessRequestId", skip_serializing_if = "Option::is_none")]
    pub secret_access_request_id: Option<i32>,
    #[serde(rename = "startDate", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<Box<models::DateTimeOffset>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::SecretAccessModelStatus>,
}

impl SecretAccessUpdateArgs {
    /// Secret Access Update paramaters
    pub fn new() -> SecretAccessUpdateArgs {
        SecretAccessUpdateArgs {
            expiration_date: None,
            response_comment: None,
            secret_access_request_id: None,
            start_date: None,
            status: None,
        }
    }
}

