/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretTemplateExtendedMappingFieldSummary : The fields that are mapped from the extended type to the secret template field
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretTemplateExtendedMappingFieldSummary {
    /// ExtendedFieldId
    #[serde(rename = "extendedFieldId", skip_serializing_if = "Option::is_none")]
    pub extended_field_id: Option<i32>,
    /// ExtendedFieldName
    #[serde(rename = "extendedFieldName", skip_serializing_if = "Option::is_none")]
    pub extended_field_name: Option<String>,
    /// ExtendedTypeId
    #[serde(rename = "extendedTypeId", skip_serializing_if = "Option::is_none")]
    pub extended_type_id: Option<i32>,
    /// SecretFieldExtendedMapId
    #[serde(rename = "secretFieldExtendedMapId", skip_serializing_if = "Option::is_none")]
    pub secret_field_extended_map_id: Option<i32>,
    /// SecretFieldId
    #[serde(rename = "secretFieldId", skip_serializing_if = "Option::is_none")]
    pub secret_field_id: Option<i32>,
    /// SecretFieldName
    #[serde(rename = "secretFieldName", skip_serializing_if = "Option::is_none")]
    pub secret_field_name: Option<String>,
}

impl SecretTemplateExtendedMappingFieldSummary {
    /// The fields that are mapped from the extended type to the secret template field
    pub fn new() -> SecretTemplateExtendedMappingFieldSummary {
        SecretTemplateExtendedMappingFieldSummary {
            extended_field_id: None,
            extended_field_name: None,
            extended_type_id: None,
            secret_field_extended_map_id: None,
            secret_field_id: None,
            secret_field_name: None,
        }
    }
}

