/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretDetailSettingsModel : Secret Detail Settings
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretDetailSettingsModel {
    /// Custom Launchers Settings
    #[serde(rename = "customLaunchersSettings", skip_serializing_if = "Option::is_none")]
    pub custom_launchers_settings: Option<Vec<models::CustomLauncherSettingsViewModel>>,
    /// Expiration Date
    #[serde(rename = "expirationDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expiration_date: Option<Option<String>>,
    /// Expiration Day Interval
    #[serde(rename = "expirationDayInterval", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expiration_day_interval: Option<Option<i32>>,
    /// Expiration Template Text
    #[serde(rename = "expirationTemplateText", skip_serializing_if = "Option::is_none")]
    pub expiration_template_text: Option<String>,
    #[serde(rename = "expirationType", skip_serializing_if = "Option::is_none")]
    pub expiration_type: Option<models::SecretDetailExpirationType>,
    #[serde(rename = "jumpboxRouteSelection", skip_serializing_if = "Option::is_none")]
    pub jumpbox_route_selection: Option<Box<models::JumpboxRouteSummaryModel>>,
    #[serde(rename = "oneTimePasswordSettings", skip_serializing_if = "Option::is_none")]
    pub one_time_password_settings: Option<Box<models::OneTimePasswordSettingsModel>>,
    #[serde(rename = "rdpLauncherSettings", skip_serializing_if = "Option::is_none")]
    pub rdp_launcher_settings: Option<Box<models::RdpLauncherSettingsModel>>,
    /// Send Email When Changed
    #[serde(rename = "sendEmailWhenChanged", skip_serializing_if = "Option::is_none")]
    pub send_email_when_changed: Option<bool>,
    /// Send Email When Heartbeat Fails
    #[serde(rename = "sendEmailWhenHeartbeatFails", skip_serializing_if = "Option::is_none")]
    pub send_email_when_heartbeat_fails: Option<bool>,
    /// Send Email When Viewed
    #[serde(rename = "sendEmailWhenViewed", skip_serializing_if = "Option::is_none")]
    pub send_email_when_viewed: Option<bool>,
    #[serde(rename = "sshLauncherSettings", skip_serializing_if = "Option::is_none")]
    pub ssh_launcher_settings: Option<Box<models::SshLauncherSettingsModel>>,
}

impl SecretDetailSettingsModel {
    /// Secret Detail Settings
    pub fn new() -> SecretDetailSettingsModel {
        SecretDetailSettingsModel {
            custom_launchers_settings: None,
            expiration_date: None,
            expiration_day_interval: None,
            expiration_template_text: None,
            expiration_type: None,
            jumpbox_route_selection: None,
            one_time_password_settings: None,
            rdp_launcher_settings: None,
            send_email_when_changed: None,
            send_email_when_heartbeat_fails: None,
            send_email_when_viewed: None,
            ssh_launcher_settings: None,
        }
    }
}

