/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretDependencyGroup : A Secret Dependency Group Object. A container for a logical collection of Secret Dependencies that use the same site.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretDependencyGroup {
    /// The Id of the Secret Dependency Group
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The name of the Secret Dependency Group
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The Id of the Site that all dependencies in this group use
    #[serde(rename = "siteId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub site_id: Option<Option<i32>>,
    /// The Name of the Site that all dependencies in this group use
    #[serde(rename = "siteName", skip_serializing_if = "Option::is_none")]
    pub site_name: Option<String>,
    /// Total Enabled Secret dependencies in this group with a Failed status
    #[serde(rename = "statusFailedCount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status_failed_count: Option<Option<i32>>,
    /// Total Enabled Secret dependencies in this group that have not yet run
    #[serde(rename = "statusNotRunCount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status_not_run_count: Option<Option<i32>>,
    /// Total Enabled Secret dependencies in this group with a Success status
    #[serde(rename = "statusSuccessCount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status_success_count: Option<Option<i32>>,
    /// Total Enabled Secret dependencies in this group
    #[serde(rename = "totalDependencies", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_dependencies: Option<Option<i32>>,
}

impl SecretDependencyGroup {
    /// A Secret Dependency Group Object. A container for a logical collection of Secret Dependencies that use the same site.
    pub fn new() -> SecretDependencyGroup {
        SecretDependencyGroup {
            id: None,
            name: None,
            site_id: None,
            site_name: None,
            status_failed_count: None,
            status_not_run_count: None,
            status_success_count: None,
            total_dependencies: None,
        }
    }
}

