/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ServerNodeStateUpdatedModel : Settings for clustering (on prem only)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerNodeStateUpdatedModel {
    /// True if clustering is enabled
    #[serde(rename = "isClusteringEnabled", skip_serializing_if = "Option::is_none")]
    pub is_clustering_enabled: Option<bool>,
    /// True is licensed and allowed to enable SQL Server replication
    #[serde(rename = "isSqlServerReplicationAllowed", skip_serializing_if = "Option::is_none")]
    pub is_sql_server_replication_allowed: Option<bool>,
    /// True if sql server replication is enabled
    #[serde(rename = "isSqlServerReplicationEnabled", skip_serializing_if = "Option::is_none")]
    pub is_sql_server_replication_enabled: Option<bool>,
    /// Set to true after certain events indicating a restart for the role is required
    #[serde(rename = "requiresRestart", skip_serializing_if = "Option::is_none")]
    pub requires_restart: Option<bool>,
}

impl ServerNodeStateUpdatedModel {
    /// Settings for clustering (on prem only)
    pub fn new() -> ServerNodeStateUpdatedModel {
        ServerNodeStateUpdatedModel {
            is_clustering_enabled: None,
            is_sql_server_replication_allowed: None,
            is_sql_server_replication_enabled: None,
            requires_restart: None,
        }
    }
}

