/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SessionTerminateResponseModel : The result of a session termination
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionTerminateResponseModel {
    /// Did the session terminate succeed
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
}

impl SessionTerminateResponseModel {
    /// The result of a session termination
    pub fn new() -> SessionTerminateResponseModel {
        SessionTerminateResponseModel {
            success: None,
        }
    }
}

