/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SettingForDisplay : Setting
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SettingForDisplay {
    /// Active
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    /// CanEdit
    #[serde(rename = "canEdit", skip_serializing_if = "Option::is_none")]
    pub can_edit: Option<bool>,
    /// CanEditValue
    #[serde(rename = "canEditValue", skip_serializing_if = "Option::is_none")]
    pub can_edit_value: Option<bool>,
    /// ChildLoadSQL
    #[serde(rename = "childLoadSQL", skip_serializing_if = "Option::is_none")]
    pub child_load_sql: Option<String>,
    /// ChildSettings
    #[serde(rename = "childSettings", skip_serializing_if = "Option::is_none")]
    pub child_settings: Option<Vec<models::Setting>>,
    /// DefaultValue
    #[serde(rename = "defaultValue", skip_serializing_if = "Option::is_none")]
    pub default_value: Option<String>,
    /// IsVisible
    #[serde(rename = "isVisible", skip_serializing_if = "Option::is_none")]
    pub is_visible: Option<bool>,
    /// NameLocalizeKey
    #[serde(rename = "nameLocalizeKey", skip_serializing_if = "Option::is_none")]
    pub name_localize_key: Option<String>,
    /// ParentSettingId
    #[serde(rename = "parentSettingId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent_setting_id: Option<Option<i32>>,
    /// RegexValidation
    #[serde(rename = "regexValidation", skip_serializing_if = "Option::is_none")]
    pub regex_validation: Option<String>,
    /// SettingId
    #[serde(rename = "settingId", skip_serializing_if = "Option::is_none")]
    pub setting_id: Option<i32>,
    /// SettingName
    #[serde(rename = "settingName", skip_serializing_if = "Option::is_none")]
    pub setting_name: Option<String>,
    /// SettingSectionId
    #[serde(rename = "settingSectionId", skip_serializing_if = "Option::is_none")]
    pub setting_section_id: Option<i32>,
    #[serde(rename = "settingType", skip_serializing_if = "Option::is_none")]
    pub setting_type: Option<models::SettingType>,
    /// SortOrder
    #[serde(rename = "sortOrder", skip_serializing_if = "Option::is_none")]
    pub sort_order: Option<i32>,
    /// SubSettingSectionId
    #[serde(rename = "subSettingSectionId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sub_setting_section_id: Option<Option<i32>>,
    /// TooltipLocalizeKey
    #[serde(rename = "tooltipLocalizeKey", skip_serializing_if = "Option::is_none")]
    pub tooltip_localize_key: Option<String>,
}

impl SettingForDisplay {
    /// Setting
    pub fn new() -> SettingForDisplay {
        SettingForDisplay {
            active: None,
            can_edit: None,
            can_edit_value: None,
            child_load_sql: None,
            child_settings: None,
            default_value: None,
            is_visible: None,
            name_localize_key: None,
            parent_setting_id: None,
            regex_validation: None,
            setting_id: None,
            setting_name: None,
            setting_section_id: None,
            setting_type: None,
            sort_order: None,
            sub_setting_section_id: None,
            tooltip_localize_key: None,
        }
    }
}

