/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SiteCreateModel : Site Create Model
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SiteCreateModel {
    /// Is Site Active
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    /// Enable CredSSP For WinRM
    #[serde(rename = "enableCredSspForWinRm", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub enable_cred_ssp_for_win_rm: Option<Option<bool>>,
    /// Enable RDP Proxy
    #[serde(rename = "enableRdpProxy", skip_serializing_if = "Option::is_none")]
    pub enable_rdp_proxy: Option<bool>,
    /// Enable SSH Proxy
    #[serde(rename = "enableSshProxy", skip_serializing_if = "Option::is_none")]
    pub enable_ssh_proxy: Option<bool>,
    /// Heartbeat Interval of Site
    #[serde(rename = "heartbeatInterval", skip_serializing_if = "Option::is_none")]
    pub heartbeat_interval: Option<i32>,
    /// Powershell Secret Id of Site if set
    #[serde(rename = "powershellSecretId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub powershell_secret_id: Option<Option<i32>>,
    /// RDP Proxy Port
    #[serde(rename = "rdpProxyPort", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rdp_proxy_port: Option<Option<i32>>,
    /// Id of Site Connector of Site
    #[serde(rename = "siteConnectorId", skip_serializing_if = "Option::is_none")]
    pub site_connector_id: Option<i32>,
    /// Name of Site
    #[serde(rename = "siteName", skip_serializing_if = "Option::is_none")]
    pub site_name: Option<String>,
    /// SSH Proxy Port
    #[serde(rename = "sshProxyPort", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ssh_proxy_port: Option<Option<i32>>,
    /// WinRM End Point URL of Site
    #[serde(rename = "winRmEndPointUrl", skip_serializing_if = "Option::is_none")]
    pub win_rm_end_point_url: Option<String>,
}

impl SiteCreateModel {
    /// Site Create Model
    pub fn new() -> SiteCreateModel {
        SiteCreateModel {
            active: None,
            enable_cred_ssp_for_win_rm: None,
            enable_rdp_proxy: None,
            enable_ssh_proxy: None,
            heartbeat_interval: None,
            powershell_secret_id: None,
            rdp_proxy_port: None,
            site_connector_id: None,
            site_name: None,
            ssh_proxy_port: None,
            win_rm_end_point_url: None,
        }
    }
}

