/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SshCommandBlocklistSummaryModel : SSH command Blocklist
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SshCommandBlocklistSummaryModel {
    /// If the Command Blocklist is enabled
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    /// A description of the Command Blocklist
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Name the Command Blocklist
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// ID of the Command Blocklist
    #[serde(rename = "sshCommandBlocklistId", skip_serializing_if = "Option::is_none")]
    pub ssh_command_blocklist_id: Option<uuid::Uuid>,
}

impl SshCommandBlocklistSummaryModel {
    /// SSH command Blocklist
    pub fn new() -> SshCommandBlocklistSummaryModel {
        SshCommandBlocklistSummaryModel {
            active: None,
            description: None,
            name: None,
            ssh_command_blocklist_id: None,
        }
    }
}

