/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SshCommandMenuPatchModel : Patch SSH Command Menu
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SshCommandMenuPatchModel {
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<Box<models::UpdateFieldValueOfBoolean>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<Box<models::UpdateFieldValueOfString>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<Box<models::UpdateFieldValueOfString>>,
    /// Ssh Command Menu Guid Id
    #[serde(rename = "sshCommandMenuGuid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ssh_command_menu_guid: Option<Option<uuid::Uuid>>,
    /// Ssh Command Menu Id
    #[serde(rename = "sshCommandMenuId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ssh_command_menu_id: Option<Option<i32>>,
    #[serde(rename = "sshCommands", skip_serializing_if = "Option::is_none")]
    pub ssh_commands: Option<Box<models::UpdateFieldValueOfString>>,
}

impl SshCommandMenuPatchModel {
    /// Patch SSH Command Menu
    pub fn new() -> SshCommandMenuPatchModel {
        SshCommandMenuPatchModel {
            active: None,
            description: None,
            name: None,
            ssh_command_menu_guid: None,
            ssh_command_menu_id: None,
            ssh_commands: None,
        }
    }
}

