/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SshCommandItemAuditSummaryModel : SSH Command Info Audits (Menu, Blocklist, Command)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SshCommandItemAuditSummaryModel {
    /// Action
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
    /// The date of the change
    #[serde(rename = "dateRecorded", skip_serializing_if = "Option::is_none")]
    pub date_recorded: Option<String>,
    /// The name of the item
    #[serde(rename = "itemName", skip_serializing_if = "Option::is_none")]
    pub item_name: Option<String>,
    /// Item Type (Command, Menu, Blocklist)
    #[serde(rename = "itemType", skip_serializing_if = "Option::is_none")]
    pub item_type: Option<String>,
    /// New Commands (Menu only)
    #[serde(rename = "newCommands", skip_serializing_if = "Option::is_none")]
    pub new_commands: Option<String>,
    /// Notes
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    /// Old Commands (Menu only)
    #[serde(rename = "oldCommands", skip_serializing_if = "Option::is_none")]
    pub old_commands: Option<String>,
    /// Display name of the user making the change
    #[serde(rename = "userDisplayName", skip_serializing_if = "Option::is_none")]
    pub user_display_name: Option<String>,
}

impl SshCommandItemAuditSummaryModel {
    /// SSH Command Info Audits (Menu, Blocklist, Command)
    pub fn new() -> SshCommandItemAuditSummaryModel {
        SshCommandItemAuditSummaryModel {
            action: None,
            date_recorded: None,
            item_name: None,
            item_type: None,
            new_commands: None,
            notes: None,
            old_commands: None,
            user_display_name: None,
        }
    }
}

