/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SshCipherSuitePatchModel : SSH Cipher Suite Patch
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SshCipherSuitePatchModel {
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<Box<models::UpdateFieldValueOfBoolean>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<Box<models::UpdateFieldValueOfString>>,
    #[serde(rename = "encryptionAlgorithms", skip_serializing_if = "Option::is_none")]
    pub encryption_algorithms: Option<Box<models::UpdateFieldValueOfString>>,
    #[serde(rename = "keyExchangeAlgorithms", skip_serializing_if = "Option::is_none")]
    pub key_exchange_algorithms: Option<Box<models::UpdateFieldValueOfString>>,
    #[serde(rename = "macAlgorithms", skip_serializing_if = "Option::is_none")]
    pub mac_algorithms: Option<Box<models::UpdateFieldValueOfString>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<Box<models::UpdateFieldValueOfString>>,
    #[serde(rename = "pkAlgorithms", skip_serializing_if = "Option::is_none")]
    pub pk_algorithms: Option<Box<models::UpdateFieldValueOfString>>,
    /// SSH Cipher Suite Id
    #[serde(rename = "sshCipherSuiteConfigurationId", skip_serializing_if = "Option::is_none")]
    pub ssh_cipher_suite_configuration_id: Option<uuid::Uuid>,
}

impl SshCipherSuitePatchModel {
    /// SSH Cipher Suite Patch
    pub fn new() -> SshCipherSuitePatchModel {
        SshCipherSuitePatchModel {
            active: None,
            description: None,
            encryption_algorithms: None,
            key_exchange_algorithms: None,
            mac_algorithms: None,
            name: None,
            pk_algorithms: None,
            ssh_cipher_suite_configuration_id: None,
        }
    }
}

