/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SyslogCefTimeZoneType : Value
/// Value
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SyslogCefTimeZoneType {
    #[serde(rename = "ServerTime")]
    ServerTime,
    #[serde(rename = "UtcTime")]
    UtcTime,

}

impl std::fmt::Display for SyslogCefTimeZoneType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ServerTime => write!(f, "ServerTime"),
            Self::UtcTime => write!(f, "UtcTime"),
        }
    }
}

impl Default for SyslogCefTimeZoneType {
    fn default() -> SyslogCefTimeZoneType {
        Self::ServerTime
    }
}

