/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SystemLogConfigurationViewModel : System Log Configuration View Model
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemLogConfigurationViewModel {
    #[serde(rename = "allowViewingOnline", skip_serializing_if = "Option::is_none")]
    pub allow_viewing_online: Option<Box<models::ViewFieldValueOfBoolean>>,
    #[serde(rename = "enableSystemLog", skip_serializing_if = "Option::is_none")]
    pub enable_system_log: Option<Box<models::ViewFieldValueOfBoolean>>,
    #[serde(rename = "maxLogLength", skip_serializing_if = "Option::is_none")]
    pub max_log_length: Option<Box<models::ViewFieldValueOfOptionalInt32>>,
    #[serde(rename = "notifyWhenShrunk", skip_serializing_if = "Option::is_none")]
    pub notify_when_shrunk: Option<Box<models::ViewFieldValueOfBoolean>>,
}

impl SystemLogConfigurationViewModel {
    /// System Log Configuration View Model
    pub fn new() -> SystemLogConfigurationViewModel {
        SystemLogConfigurationViewModel {
            allow_viewing_online: None,
            enable_system_log: None,
            max_log_length: None,
            notify_when_shrunk: None,
        }
    }
}

