/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TeamCategorizedListSummary : TeamCategorizedListSummary
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamCategorizedListSummary {
    /// Lists
    #[serde(rename = "lists", skip_serializing_if = "Option::is_none")]
    pub lists: Option<Vec<models::SimpleCategorizedList>>,
    /// TeamId
    #[serde(rename = "teamId", skip_serializing_if = "Option::is_none")]
    pub team_id: Option<i32>,
}

impl TeamCategorizedListSummary {
    /// TeamCategorizedListSummary
    pub fn new() -> TeamCategorizedListSummary {
        TeamCategorizedListSummary {
            lists: None,
            team_id: None,
        }
    }
}

