/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TeamDetailModel : Query results
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamDetailModel {
    /// Active
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    /// ConcurrencyId
    #[serde(rename = "concurrencyId", skip_serializing_if = "Option::is_none")]
    pub concurrency_id: Option<String>,
    /// Domain Id
    #[serde(rename = "domainId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub domain_id: Option<Option<i32>>,
    /// Domain Name
    #[serde(rename = "domainName", skip_serializing_if = "Option::is_none")]
    pub domain_name: Option<String>,
    /// Should Restrict Lists
    #[serde(rename = "shouldRestrictLists", skip_serializing_if = "Option::is_none")]
    pub should_restrict_lists: Option<bool>,
    /// Should Restrict Sites
    #[serde(rename = "shouldRestrictSites", skip_serializing_if = "Option::is_none")]
    pub should_restrict_sites: Option<bool>,
    /// Team Description
    #[serde(rename = "teamDescription", skip_serializing_if = "Option::is_none")]
    pub team_description: Option<String>,
    /// Team Id
    #[serde(rename = "teamId", skip_serializing_if = "Option::is_none")]
    pub team_id: Option<i32>,
    /// Team Name
    #[serde(rename = "teamName", skip_serializing_if = "Option::is_none")]
    pub team_name: Option<String>,
}

impl TeamDetailModel {
    /// Query results
    pub fn new() -> TeamDetailModel {
        TeamDetailModel {
            active: None,
            concurrency_id: None,
            domain_id: None,
            domain_name: None,
            should_restrict_lists: None,
            should_restrict_sites: None,
            team_description: None,
            team_id: None,
            team_name: None,
        }
    }
}

