/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TestRadiusLoginRequestModel : Test Radius Login Request
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TestRadiusLoginRequestModel {
    /// Password for Radius Login Test
    #[serde(rename = "radiusPassword", skip_serializing_if = "Option::is_none")]
    pub radius_password: Option<String>,
    /// Username for Radius Login Test
    #[serde(rename = "radiusUsername", skip_serializing_if = "Option::is_none")]
    pub radius_username: Option<String>,
}

impl TestRadiusLoginRequestModel {
    /// Test Radius Login Request
    pub fn new() -> TestRadiusLoginRequestModel {
        TestRadiusLoginRequestModel {
            radius_password: None,
            radius_username: None,
        }
    }
}

