/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TwoFactorResetType : Available types of 2FA options that can be reset
/// Available types of 2FA options that can be reset
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TwoFactorResetType {
    #[serde(rename = "Oath")]
    Oath,
    #[serde(rename = "Fido")]
    Fido,

}

impl std::fmt::Display for TwoFactorResetType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Oath => write!(f, "Oath"),
            Self::Fido => write!(f, "Fido"),
        }
    }
}

impl Default for TwoFactorResetType {
    fn default() -> TwoFactorResetType {
        Self::Oath
    }
}

