/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateFieldValueOfPasswordHashType : Hash to be used when generating the One Time Password, updated when one time password is enabled
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateFieldValueOfPasswordHashType {
    /// Dirty
    #[serde(rename = "dirty", skip_serializing_if = "Option::is_none")]
    pub dirty: Option<bool>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<models::PasswordHashType>,
}

impl UpdateFieldValueOfPasswordHashType {
    /// Hash to be used when generating the One Time Password, updated when one time password is enabled
    pub fn new() -> UpdateFieldValueOfPasswordHashType {
        UpdateFieldValueOfPasswordHashType {
            dirty: None,
            value: None,
        }
    }
}

