/*
 * Secret Server Rest API
 *
 * REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.
 *
 * The version of the OpenAPI document: 11.7.61
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ViewFieldLink : AdditionalLinks
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ViewFieldLink {
    /// IsExternal
    #[serde(rename = "isExternal", skip_serializing_if = "Option::is_none")]
    pub is_external: Option<bool>,
    /// LinkText
    #[serde(rename = "linkText", skip_serializing_if = "Option::is_none")]
    pub link_text: Option<String>,
    /// Url
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl ViewFieldLink {
    /// AdditionalLinks
    pub fn new() -> ViewFieldLink {
        ViewFieldLink {
            is_external: None,
            link_text: None,
            url: None,
        }
    }
}

